### ISSUE TITLE
Question: How to import multiple files or multiple directories?

### ISSUE THREAD

**Issue by angeloklin** [biolab/orange3-text#101]
Hello,
  Nice to see that we got a very fresh version.

  Question: Is it possible to load multiple files and multiple directories for Text Mining?
  I tried opening the whole level up, no luck
  I tried compressing on a file.tsv.gz using tar, no luck

  As it is a group of directories with multiple files (one per document) it would be normal to create a Corpus from such structure. If not, what would work?

  I have something like:

```
Groups
+- Group_1
|  +- 1999
|  |  +- file_1.txt (any valid extension)
|  |  +- . . .
|  +- 2000
|  +- . . .
+- Group_2
    +- 1982
    +- 1985
    +- . . .
```

Thanks and Regards

**Comment by nikicc** [comment]
@angeloklin unfortunately we do not support this yet. This is something we were thinking about on several occasions. Until this is implemented, I don't think there is any other way than concatenating them manually into one of the Orange's supported files (csv, tab, ...).

**Comment by kernc** [comment]
Interim, you could construct a single CSV of all documents:
```text
group_id,year,filename,contents
group_1,1999,file1.txt,"whole file1 contents"
group_1,1999,file2.txt,"whole file2 contents"
...
group_n,2025,fileF.txt,"whole fileF contents"
```
You would have to ensure the quotes in whole file contents are properly escaped.

**Comment by angeloklin** [comment]
@nikicc, @kernc Thanks for your reply.
Concatenating is not ideal, as there are 25,000 docs of variable size, on a total of 3.5Gb.

Two other ideas:
1) Would be possible to write a Python script and build a Data Table?
2) I saw the SQL Table widget, but could not identify which databases it can talk with. Options that come to mind in the open surce would be mysql, posgre and mongo.

regards

**Comment by nikicc** [comment]
> Would be possible to write a Python script and build a Data Table?

Yes, that's possible. This is far from ideal but here is a simple example on how to achieve this in the current version. Open the Python Script widget and paste this code:
```py
import os
import numpy as np
from Orange.data.domain import Domain, StringVariable
from orangecontrib.text.corpus import Corpus


PATH = '<the-path-to-the-group-folder>'
MAX_DOC = 1000

# create Orange's domain; all features will be in metas
meta_attrs = [StringVariable('group'), StringVariable('year'), StringVariable('filename'), StringVariable('content')]
domain = Domain(attributes=[], class_vars=[], metas=meta_attrs)

# create numpy array for storing the data
data = np.empty((MAX_DOC, 4), dtype=object)
doc_ind = 0

class BreakIt(Exception): pass    # enable stopping
try:
    for dir, _, files in os.walk(PATH):                # walk through all sub-directories
        for file in files:                             # and through all files inside sub-directories
            if file.endswith('.txt'):                  # if the type matches
                group, year = dir.split(os.sep)[-2:]   # parse group and year

                # read file's content and delete \n characters
                with open(os.path.join(dir, file), 'r') as f:
                    content = f.read().replace('\n', ' ')
            
                # store the data to numpy matrix    
                data[doc_ind, 0] = group
                data[doc_ind, 1] = year
                data[doc_ind, 2] = file
                data[doc_ind, 3] = content
                doc_ind += 1
        
                if doc_ind == MAX_DOC:    # if you loaded enough, stop
                    raise BreakIt
except BreakIt:
    pass
                
# truncate empty lines
data = data[:doc_ind, :]
print('Loaded {} documents.'.format(doc_ind))

# create corpus
corp = Corpus.from_numpy(domain, X=np.empty((doc_ind, 0)), metas=data)
# set which features to use for text mining; use only content
corp.set_text_features(meta_attrs[-1:])

# send the data to the output
out_object = corp
```

What this does is walks through the folder hierarchy and loads all txt files. All you have to set is the `PATH` variable at the top of the script, which should point to the root `groups` folder. Note that there is also a `MAX_DOC` variable that stops loading after `MAX_DOC` number of documents have been loaded.

Once you load the documents using this code a Corpus will be present on the output signal `out_object` of the widget. You can connect it to other text widgets as you would normally do, just make sure that you are using `out_object` and not `out_data` (this could be changed by clicking on the line between the two widgets).

I should also warn you that you might encounter some memory issues when trying to load 3.5 GB data set into Orange. I suggest you start with some small subset of documents. Also let us know, how this will go.

> Update: I later checked and found support for postgre via a python library. I wonder if is just a matter of having a library and what other steps to make a db2 available.

I don't know much about SQL support. @lanzagar can you help?

**Comment by bandaruvenky** [comment]
@nikicc @kernc  Please suggest if there is a widget in latest version(using 3.4).

I am facing below error while executing the script.
ImportError: No module named 'orangecontrib.text'

I am new to Python, googled about the module but couldn't get a reference to install it. 
Can you provide through some light on this.

**Comment by nikicc** [comment]
@bandaruvenky unfortunately, there isn't yet.

Once it's made, this issue will be closed, so you should be notified about this.

**Comment by nikicc** [comment]
@angeloklin, @bandaruvenky we added the widget called `Import Documents` that can perform this task. It can be found in the `0.2.5` version of text addon that should appear on pypi and conda-forge in a day or so.

**Comment by oli666** [comment]
The "Import Documents" widget cannot, however, import csv files due to the restriction to txt, pdf etc. extensions. Is there a reason to have this restriction?

**Comment by ajdapretnar** [comment]
Import Documents is intended for importing text files, hence the restriction. To import .csv, use the File widget.

**Comment by viniciusgomesbatista** [comment]
You can use the Add-ons... in Options and enable the spectroscopy. Then you can use de widget Multifile and then Data Table.
