### ISSUE TITLE
Corpus or Text Widget do  not appear in Orange 3.36.2

### ISSUE THREAD

**Issue by mcanally-lewis** [biolab/orange3-text#1035]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Orange version:**
Orange - About - version number.

**Text add-on version:**
Options - Add-ons - version number.

**Screenshots**

**Operating system:**
Windows, OSX or Linux? Which version?

**Additional context**

**Comment by mcanally-lewis** [comment]
Corpus or Text Widget do not appear in Orange 3.36.2

System: Windows 11

**Comment by PrimozGodec** [comment]
Thank you for reporting the bug. Can you tell us how did you installed Orange and what version of text add-on you have (Options - Add-ons - version number)?

**Comment by ajdapretnar** [comment]
Close as stale.
