### ISSUE TITLE
Annotated Corpus Map: add legend for cluster labels

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-text#1044]
**Is your feature request related to a problem? Please describe.**
When observing ACM, it is unclear which cluster corresponds to which label (C1, C2, C3 ...).

**Describe the solution you'd like**
Add a legend or a meta attributes to color by.

**Describe alternatives you've considered**
/

**Comment by wvdvegte** [comment]
I think this has been resolved, right? If you select "Color points by cluster" you can see which cluster has which color.

**Comment by ajdapretnar** [comment]
I did not even see this option. I was looking under the classic "Color". Thanks!
