### ISSUE TITLE
Word Cloud: annoying white line at the top

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-text#204]
Word Cloud plot has two bugs.
1.) The visualization is not always immediately plotted and one needs to press 'Regenerate word cloud' for anything to be displayed.
2.) The annoying small line of mirrored text when the visualization is resized.

**Comment by ajdapretnar** [comment]
Haven't encountered 1. in a while. 2. is still an issue.

**Comment by puripant** [comment]
Can you add more descriptions, possibly with screenshots? In particular, which white line at the top?

I cannot replicate either bug. I cannot even resize the window; the program crashed with "Segmentation fault: 11" error.

**Comment by ajdapretnar** [comment]
Segementation fault is due to a bad version of PyQt. I recommend installing PyQt5 = 5.12.3.

Here is the screenshot:
<img width="659" alt="Screen Shot 2019-10-14 at 09 31 28" src="https://user-images.githubusercontent.com/12524972/66735088-0c331b80-ee6e-11e9-8898-d2d3f068dd91.png">

The issue is that two images get drawn at the same time, so when as WC is full (lots of words), you might even see a bit of the words on the top line.
