### ISSUE TITLE
Preprocess Text: empty Tagger (Stanford) results in segfault 

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-text#205]
Corpus (bookexcerpts) - Preprocess Text - turn on POS Tagger - select Tagger (window opens) - don't select any tagger, just use cancel).

Procedure results in segfault.

Perhaps disable Tagger if Model empty or otherwise prevent segfaulting.

**Comment by kernc** [comment]
Can you step through it to see where it crashes? Can't reproduce on Linux, PyQt5.8.
