### ISSUE TITLE
Preprocess Text Refactoring

### ISSUE THREAD

**Issue by nikicc** [biolab/orange3-text#209]
##### Text version

2.4.dev

##### Proposed Layout
* Transformation
* Tokenization
* Stopwords, Lexicon, Regex filtering
* POS tagging
* Normalization
* N-Grams
* DF, Max Tokens filter [Output]

##### Fixes
* Filtering on tokens not lemmas.
* DF, Max Tokens filtering on N-Grams.

##### Doesn't Fix
* N-Grams are built from non-consecutive words in text due to filtering in step 3.

**Comment by kernc** [comment]
From https://github.com/biolab/orange3-text/issues/210:
> Refactor preprocess text GUI to make in smaller and more Orange-like: methods in dropdowns, regex input filed besides and greyed out when not relevant, no ON/OFF buttons, just control area, ...

**Comment by ajdapretnar** [comment]
This would be made redundant by #210.
