### ISSUE TITLE
Preprocess Text: Refactor

### ISSUE THREAD

**Issue by nikicc** [biolab/orange3-text#210]
##### Text version

2.4.dev

##### Expected behavior
Refactor preprocess text GUI to make in smaller and more Orange-like: methods in dropdowns, regex input filed besides and greyed out when not relevant, no ON/OFF buttons, just control area, ...

**Comment by kernc** [comment]
Duplicate of https://github.com/biolab/orange3-text/issues/209?

**Comment by kernc** [comment]
Duplicate of https://github.com/biolab/orange3-text/issues/209?

**Comment by ajdapretnar** [comment]
I vote for making Preprocess Text the way Preprocess is done in Orange. This will allow much greater flexibility + creating custom preprocessing pipeline is essential for text mining.
Widget should display a sample of preprocessed tokens in control area.

**Comment by ajdapretnar** [comment]
![preprocess-text](https://user-images.githubusercontent.com/12524972/48421201-4ecf0e00-e75c-11e8-8b41-30a2e3f3edef.png)

**Comment by gengyabc** [comment]
And I find the widget download all the files in main thread, which makes me thought my computer is dead. Could the file download moved to other thread?

**Comment by ajdapretnar** [comment]
@gengyabc I think it is best to open a separate issue for this.

Main issue implemented in #506.
