### ISSUE TITLE
GeoMap Counts Don't Match Number of Instances on Output

### ISSUE THREAD

**Issue by nikicc** [biolab/orange3-text#219]
##### Text version

0.2.4.dev

##### Expected behavior
Count shown on map should match the number of instances on output.

##### Actual behavior
It does not. GeoMap indicates on three instances about Australia while we get 25 instances on output.

##### Steps to reproduce the behavior
![screen shot 2017-03-31 at 15 35 11](https://cloud.githubusercontent.com/assets/713026/24552687/bd406a80-1627-11e7-805f-a1bfd0d13391.png)

##### Additional info
Irrelevant after #218?

**Comment by kernc** [comment]
Fixed in #218
