### ISSUE TITLE
NLTK Download Can Cause Orange To Hang While Starting

### ISSUE THREAD

**Issue by nikicc** [biolab/orange3-text#223]
##### Expected behavior
Orange starts normally when internet connection doesn't respond even when NLTK data is not yet downloaded. 

##### Actual behavior
If we do not yet have NLTK data loaded and we are connected to the internet but the connection doesn't respond (use nonexistent DNS) Orange hangs for ~1m while starting since it wants to load NLTK data.

##### Steps to reproduce the behavior
Delete NLTK data, provide invalid DNS and start Orange.

**Comment by kernc** [comment]
https://github.com/biolab/orange3-geo/commit/deffbdc20bad0b268da5352981ead092c9b933c3 parses some 50 MB of JSON data, would-be good for some extra 5 seconds, in an async manner, making the app only blockingly stall when the particular function is called that needs it.
