### ISSUE TITLE
Networks from Documents

### ISSUE THREAD

**Issue by nikicc** [biolab/orange3-text#228]
##### Usecase
One could create network of twitter users where the edges would connect users who communicate on twitter.

**Comment by ajdapretnar** [comment]
An idea: could we perhaps add some useful scripts to Python Script widget, so users could load them upon request? This would avoid us having too many very specific widgets. But again, it's just an idea. @janezd @astaric

**Comment by nikicc** [comment]
Maybe, instead, this could become a more general widget for creating networks out of documents? So one could create networks of word co-occurrences either in a sentence (or a neighbouring window), networks of people (named entities?) that occur in the same sentence, etc.

**Comment by ajdapretnar** [comment]
Development guide for this widget:

- Compute word co-occurrence.
- In the widget, the user can set the threshold for the minimum number of words that documents have to share to create an edge.
- Output the network with corresponding node data.

Easy peasy.
