### ISSUE TITLE
Geomap scale

### ISSUE THREAD

**Issue by nikicc** [biolab/orange3-text#25]
Geomap scale has two problems:
* the scale seems too small; e.i. although the Syria has count 119, the largest number is, I assume, 12,
* numbers on the scale with more than one digit seem to show only the first digit.
![screen shot 2016-01-06 at 20 33 16](https://cloud.githubusercontent.com/assets/713026/12152412/d07f443e-b4b4-11e5-9c01-9bcad7c1c07a.png)

This can be reproduced by searching for `refugees` in NY Times widget and loading some ~500 documents.

**Comment by ajdapretnar** [comment]
Scale gets squashed into a dot when all values are the same. I don't see the dot on Windows because of the re-sizing issue, but @nikicc might have a screenshot for this one.

**Comment by nikicc** [comment]
This happens if all the counts are the same:
![screen shot 2016-03-29 at 13 29 11](https://cloud.githubusercontent.com/assets/713026/14106562/42f390e0-f5b2-11e5-9911-d761da1ce812.png)

**Comment by kernc** [comment]
Minor, upstream, deferred. jVectorMap was a poor choice in the first place. Don't know where Highmaps were hiding at the time. :disappointed:
