### ISSUE TITLE
Predictions: work on text data

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-text#251]
##### Text version

0.2.3

##### Orange version

3.5.dev

##### Expected behavior
Predict class on new data.

##### Actual behavior
Predictions fail.

##### Steps to reproduce the behavior
Train data: Grimm-tales-short.pickle
Test data: Andersen.pickle
Corpus - Preprocess Text - BoW - LogReg - Predictions
Corpus(1) - Predictions

##### Additional info (worksheets, data, screenshots, ...)
<img width="1100" alt="screen shot 2017-05-25 at 12 13 38" src="https://cloud.githubusercontent.com/assets/12524972/26446283/a6f826c2-4143-11e7-8ddc-da7d92e5d81a.png">

**Comment by nikicc** [comment]
The problem with this is that `Lookup` (`Orange.preprocess.remove`) doesn't work with sparse.

**Comment by nikicc** [comment]
Problems with Lookup have been resolved in https://github.com/biolab/orange3/pull/2364. Also, working with tabs instead of pickles prevents this to happen.
