### ISSUE TITLE
Open documentation on F1

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-text#254]
##### Text version

0.2.3

##### Orange version

3.5.0

##### Expected behavior
Documentation opens on F1.

##### Actual behavior
'No documentation for this widget yet.'

Even though there is.

##### Steps to reproduce the behavior
Corpus, press F1.

**Comment by jerneju** [comment]
![screenshot_20170531_124619](https://cloud.githubusercontent.com/assets/22157215/26628635/29599d3e-45ff-11e7-86b8-02c4cd13e6e7.png)
