### ISSUE TITLE
Corpus Viewer: wrong settings

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-text#255]
Corpus Viewer shouldn't store the document selection so rigidly.

For example, I select a subset of documents. Then I select the 8th document in the subset.
If I change the subset, the 8th document of the new subset will be selected. If my subset has less than 8 documents, no documents will be selected and none will be displayed in Corpus Viewer.

This is quite unpractical for browsing, I think, but I'm not sure how to formalize it.
If a subset changes, clear the selection?
Would this make sense?
Perhaps a discussion with @jerneju and @nikicc?

**Comment by kernc** [comment]
Some discussion of this issue in here: https://github.com/biolab/orange3/pull/2301#issuecomment-301078702
A proposed workaround I consider a huge hack, and it wouldn't really work without multiple distinct, per-setting settingsHandlers: https://github.com/biolab/orange3/pull/2301#issuecomment-304228325
A hack workaround for DomainContextHandlers, but which doesn't retain the selection once the same data is passed in again (Canvas passes None beforehand): https://github.com/biolab/orange3/pull/2301#discussion_r118804152
