### ISSUE TITLE
Reference term LSA

### ISSUE THREAD

**Issue by aishaFT** [biolab/orange3-text#278]
##### Expected behavior

We would like to to measure coherence of uttered speech to questions or a reference term.

##### Actual behavior

So far,  there is no way of include such a reference term or sentence.

**Comment by nikicc** [comment]
@aishaFT we implemented the additional output (called `All Topics`). I think this is what you had in mind, right?

This code will be released over this weekend (expect a new version `0.2.5`). Once it's out, would you try if things work out for you? If not, feel free to reopen this issue and describe more thoroughly what is missing or doesn't work.
