### ISSUE TITLE
After installing orange3-text can not open orange3

### ISSUE THREAD

**Issue by linbojin** [biolab/orange3-text#285]
##### Text version

Latest Orange3-Text-0.2.4

##### Orange version

Latest Orange3.4.4 / Anaconda 4.4.0 python 3.6

##### Expected behavior
Open Orange3 correctly

##### Actual behavior
Always stuck in the loading stage:
![image](https://user-images.githubusercontent.com/5894707/28499412-c64a7f0c-6fe7-11e7-9995-b520b0e457e4.png)
![image](https://user-images.githubusercontent.com/5894707/28499418-0951cb70-6fe8-11e7-8dd2-83c789d74593.png)

##### Steps to reproduce the behavior
Just install Orange3-Text and open Orange3-Text.

##### Additional info (worksheets, data, screenshots, ...)
I reinstalled Orange3 and reinstalled Orange3-Text (by menu-Option-Adds-on as well as `/Applications/Orange3.app/Contents/MacOS/pip install Orange3-Text`) many times, but still have same problem.

My Mac:
![image](https://user-images.githubusercontent.com/5894707/28499425-3fe6a34a-6fe8-11e7-8c86-823e3500a6f3.png)

BTW, Thanks for this awesome software, it's realllly useful.

By Linbo

**Comment by linbojin** [comment]
After stuck for ~20 mins, it opened correctly. I think it's because the network of GFW (it's very slow to download some components). I think it's better to add some instructions about this problem.

**Comment by nikicc** [comment]
Yes, the problem was most probably due to the slow internet connection. After you install text and open it for the first time, it downloads some required data from NLTK, which might cause slow start-ups.

This is the duplicate of https://github.com/biolab/orange3-text/issues/223, which unfortunately hasn't yet been addressed.
