### ISSUE TITLE
Sentiment Analysis: icon is very similar to other icon

### ISSUE THREAD

**Issue by jerneju** [biolab/orange3-text#293]
##### Text version
current

##### Orange version
current

##### Expected behavior
I am probably nitpicking. But however icons probably should not be too similar to each other.

##### Actual behavior
Icon **Sentiment Analysis** is very similar to **Theatre Classique** from 3rd Party Add-on **Textable Prototypes**.

##### Additional info (worksheets, data, screenshots, ...)
![screenshot_20170728_105654](https://user-images.githubusercontent.com/22157215/28710696-53c9552e-7385-11e7-87c3-92bacef6bd1c.png)

**Comment by ajdapretnar** [comment]
I'm not sure we should concern ourselves with this. Textable is not our add-on and we cannot control which icon they use.

What do you think, @nikicc and @BlazZupan?

**Comment by nikicc** [comment]
I wouldn't worry about this too much.
