### ISSUE TITLE
Tweet Profile again stopped working

### ISSUE THREAD

**Issue by riksri1** [biolab/orange3-text#295]
##### Text version
0.2.5

##### Orange version
3.4.5

##### Expected behavior
Depict the distributions

##### Actual behavior
Stopped working

##### Additional info (worksheets, data, screenshots, ...)

![orange issue](https://user-images.githubusercontent.com/1832806/28751164-869418d0-7511-11e7-80ba-c80fc8985637.png)

**Comment by nikicc** [comment]
@riksri1 sorry for your problems! I cannot reproduce this either on `0.2.5` nor on `0.2.3`. Also, the server logs look ok. Does the issue still persist for you?

**Comment by riksri1** [comment]
Yes its working but very slow. Sometimes getting the same error and need to restart all over again

**Comment by nikicc** [comment]
I'm afraid there isn't much that could be done about the speed until we move this to the new server architecture. Hopefully, we would manage to move it in the following weeks.

**Comment by ajdapretnar** [comment]
I can't reproduce either. It might be a RAM issue?

**Comment by ajdapretnar** [comment]
@acopar @nikicc Has this been moved already?

**Comment by riksri1** [comment]
Yes it works now

**Comment by riksri1** [comment]
Is there a method to connect R with orange?

**Comment by riksri1** [comment]
Or any other web scraping method?

**Comment by ajdapretnar** [comment]
Orange uses Python and you can use Python Script widget to access Python libraries.

**Comment by riksri1** [comment]
Do we have any widget for web scraping then?

**Comment by kernc** [comment]
The [widget for web scraping](https://github.com/biolab/orange3-text/pull/47) is not ready yet. :laughing:
 
You can [scrape documents](http://newspaper.readthedocs.io/en/latest/) with custom code into txt files which you can load with _Import Documents_ widget.

**Comment by ajdapretnar** [comment]
This will be solved when and if #214 is implemented.
