### ISSUE TITLE
Sentiment-weighted word clouds

### ISSUE THREAD

**Issue by bernardofn** [biolab/orange3-text#311]
##### Expected behavior
Enhance the widget Word Cloud with sentiment-weights. 

##### Actual behavior
Word clouds only represent tokens frequencies.

##### Steps to reproduce the behavior
It could just introduce a "color by" in word clouds.

##### Additional info (worksheets, data, screenshots, ...)
Example of output: 
https://hackernoon.com/using-machine-learning-to-visualize-customer-preferences-6a007cfb9b97
http://www.nytimes.com/interactive/2012/09/06/us/politics/convention-word-counts.html

**Comment by ajdapretnar** [comment]
@bernardofn Thank you for a good idea! We have discussed this and it turns out it is not completely trivial. We need to think a bit more what would be the best way to implement it. Stay tuned. :)

**Comment by bernardofn** [comment]
No worries. Just wanted to share with you an interesting visual I recently found.

I will stay tuned :-)

Sent from my iPhone

On 8 Sep 2017, at 09:50, Ajda <notifications@github.com<mailto:notifications@github.com>> wrote:


@bernardofn<https://github.com/bernardofn> Thank you for a good idea! We have discussed this and it turns out it is not completely trivial. We need to think a bit more what would be the best way to implement it. Stay tuned. :)

**Comment by ajdapretnar** [comment]
We have recently discussed this and sentiment-weighted words clouds are not a realistic option in Orange. This is because Sentiment Analysis gives scores per document, not per word. The option that we discussed was to have an option to color by a discrete variable, where the color would correspond to the majority class and opacity to its prevalence.

**Comment by ajdapretnar** [comment]
Opening a new issue for this one.
