### ISSUE TITLE
SVM Fails on Election Tweets Data Set

### ISSUE THREAD

**Issue by nikicc** [biolab/orange3-text#312]
##### Text version

0.2.6.dev0+524376

##### Orange version

3.6.0.dev0+1a4652a

##### Expected behavior
SVM works on election data set.

##### Actual behavior
SVM fails with `Non-zero offset in normalization of sparse data`

##### Steps to reproduce the behavior
![screen shot 2017-09-08 at 13 00 13](https://user-images.githubusercontent.com/713026/30211023-7ee3fd8c-949f-11e7-91f2-9fcab585f932.png)

**Comment by fotisz** [comment]
I am still getting the same issue in 3.14 ... has this now been fixed?

**Comment by ajdapretnar** [comment]
No, I don't think it has. Probably this issue needs to be transferred to core Orange and fixed in SVM, rather than in Text.

**Comment by AndrejaKovacic** [comment]
Fixed via  #3898 in core.
