### ISSUE TITLE
Lexicon, Whitepaper, reference, or documentation for Twitter Profiler

### ISSUE THREAD

**Issue by DuyVietNguyen** [biolab/orange3-text#316]
Hello! I am doing research and need to observe the emotion scoring mechanism within the Twitter Profiler widget. Is there a lexicon, whitepaper, reference, or documentation someone could point me to? The sentiment analysis widget seems pretty straight forward, but the Twitter Profiler remains a black box. 

Thanks in advance, Orange3 rocks!

**Comment by nikicc** [comment]
Tweet Profiler uses a character-based recurrent neaural networks that were trained in a distant supervision manner. Basically, you take a lot of tweets with emotional hashtags and then train a NN to recoginze which hashtag was used. Acuraccy wise, our models achieve micro F1 score of about `70%`.

Regarding the witepaper reference, our paper is currectly under a peer-review processes, so I'm not sure if I'm allowed to share it yet. Once it get's published (🤞) we will link to it.

**Comment by DuyVietNguyen** [comment]
Wow thanks for the prompt reply! I just happen to come across some of your other github publishes on my own research journey and I just want to say that I'm a fan. Your guys work in this combinatoric graph embeddings or visual programming and node based programming workflows are the future.  Break a leg with your pending publication and viva la Orange!

**Comment by nikicc** [comment]
Nice to hear this, thanks!

I'll keep this issue open just as a reminder not to forget to link to the paper.

**Comment by ajdapretnar** [comment]
@nikicc Would this be the one?
https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=8295234

**Comment by nikicc** [comment]
@ajdapretnar yup, that's the one :)

**Comment by ajdapretnar** [comment]
I'll put it in the docs.

**Comment by ajdapretnar** [comment]
Fixed in 1fea3bce06827bda223d496040327fdcbb1bd1a8.
