### ISSUE TITLE
Concordances Need Report, Perhaps Also Additional Output

### ISSUE THREAD

**Issue by nikicc** [biolab/orange3-text#317]
##### Expected behavior
One is able to somehow _export_ the results of concordances widget.

##### Actual behavior
No way to export anything, one can only observe.

##### Proposal Solution
Concordances need a report option. Perhaps, it would also make sense to export new corpus with concordances as documents?

**Comment by ajdapretnar** [comment]
Output added in #371. Report added in #321.
