### ISSUE TITLE
Extract XML with non alphanumeric symbol in XML element

### ISSUE THREAD

**Issue by darjusp** [biolab/orange3-text#318]
##### Text version

0.2.5

##### Orange version

3.4.5

##### Expected behavior
Is there a way with extract XML to find xml elements by its name, if name consist of at least one non letter or number, for example dast(-). 
If element name is, lets say, `<scopus>` it will locate all entities, if its `<scopus-id>` it will locate none

##### Actual behavior
please look at the attachment.
If asked to extract "scopus", which is only a part of full needed element, then we get 4 elements, but if asked to extract  "scopus-id", which is full name of element, then we get 0. I feel its because search process breaks after finding dash in between.

##### Steps to reproduce the behavior
Here is the excerpt from the XML file I was using

```xml
<reference id="1">
<sourcetitle>Nothing important</sourcetitle>
<pubmed-id>5345491</pubmed-id>
<scopus-id>0014608620</scopus-id>
<scopus-eid>2-s2.0-0014608620</scopus-eid>
</reference>
<reference id="2">
<sourcetitle>Acta Dermato-Venereologica</sourcetitle>
<pubmed-id>46678</pubmed-id>
<scopus-id>0016663636</scopus-id>
<scopus-eid>2-s2.0-0016663636</scopus-eid>
</reference>
```
##### Additional info (worksheets, data, screenshots, ...)

![screen shot 2017-10-13 at 12 19 38](https://user-images.githubusercontent.com/10597360/31539339-f56a4d30-b010-11e7-8b78-2a6b8d9bed86.png)

**Comment by kernc** [comment]
For the time being, XML documents are considered as plain text, not markup. I don't think it can be done as Regexp tokenizer in Preprocess Text widget just does simple selection (without sufficient lookback, backreferences, or replacement).

If you're on Unix-like system, you can filter the XML through a pipeline such as:
```bash
cat myfile.xml | grep -oP '<(\w+)>.*?</(\1)>' | sed -r 's,<(\w+)>(.*)</\1>,\2,g'
```
For your above example, this will print:
```text
Nothing important
Acta Dermato-Venereologica
```
If you have multiple such files in a directory:
```bash
mkdir -p extracted
for file in *.xml; do cat "$file" | ... > "extracted/$file.txt"; done

**Comment by darjusp** [comment]
Hi, Thanks for the answer. Sorry it seems I wasn't clear enough. I attached the image and explained it in "Actual behavior" of the issue

**Comment by kernc** [comment]
Oh, I believe these widgets are from Orange-Textable add-on, not Orange3-Text: https://github.com/axanthos/orange3-textable Perhaps raise the issue there.
