### ISSUE TITLE
Copying corpus sometimes fails

### ISSUE THREAD

**Issue by jerneju** [biolab/orange3-text#324]
##### Text version
Current (~**0.2.5**) and older

##### Orange version
master

##### Expected behavior
```python
corpus = Corpus(...)
new_corpus = corpus.copy()
```
That should work and not raise an error.

##### Actual behavior

> orangecontrib.text.corpus in set_text_features at line 90
>    raise ValueError('Feature "{}" not found.'.format(f))
> orangecontrib.text.corpus in __init__ at line 73
>    self.set_text_features(text_features)
> orangecontrib.text.corpus in copy at line 321
>    self.W.copy(), copy(self.text_features))
> orangecontrib.text.widgets.owpreprocess in set_data at line 598
>    self.corpus = data.copy() if data is not None else None

https://sentry.io/biolab/orange3-text-bl/issues/399242697/

**Comment by jerneju** [comment]
`data.transform(new_domain)` does not update `text_features`.

**Comment by nikicc** [comment]
Could you fix `transform` on `Corpus` to retain them?

**Comment by jerneju** [comment]
Yes.
