### ISSUE TITLE
[QUESTION] How to import dataset from csv

### ISSUE THREAD

**Issue by gtzinos** [biolab/orange3-text#326]
[wdbc.csv.tar.gz](https://github.com/biolab/orange3-text/files/1463518/wdbc.csv.tar.gz)
Orange Version: 3.7.0

Hi all,

I am using your great library some days ago and i facing an issue with import data. All working great when i use your existing datasets but when i am trying to use a custom csv file then your classifiers throws errors. Lets give an example (*I attached the dataset to this issue):

```
import Orange

# load the dataset from csv file
dataset = Orange.data.Table('./wdbc.csv')

print(dataset)

# Define CN2 Learner
learner = Orange.classification.CN2Learner()


# Train learner
classifier = learner(dataset)

# Cross validating results
res = Orange.evaluation.testing.CrossValidation(dataset, [learner], k=5)
```

When i execute the code it throws this exception:
```

File "/usr/local/lib/python3.5/dist-packages/Orange/base.py", line 105, in __call__
    raise ValueError(self.learner_adequacy_err_msg)
ValueError: Discrete class variable expected.
```

**Comment by kernc** [comment]
Continued in https://github.com/biolab/orange3/issues/2768.
