### ISSUE TITLE
Stopwords example not installed

### ISSUE THREAD

**Issue by ftastisch** [biolab/orange3-text#331]
##### Orange version

0.3.0

##### Expected behavior
create example stopwords-file(s) in /AppDate/Roaming/... during installation in Orange3

##### Actual behavior
stopwords directory remains empty 

##### Steps to reproduce the behavior
install Add-on in Orange

##### Additional info (worksheets, data, screenshots, ...)

Hi!

Where can I find the files that should be copied to this directory in the repository? I am new to Orange and would like to test some of the features.

Thank you very much!

Best regards,
Fo

**Comment by ftastisch** [comment]
Sorry, I think I made a mistake in the description.
There are corpora from NLTK in the /AppDate/Roaming/... directory, but I cannot apply them the way it is shown in this video: https://www.youtube.com/watch?v=V70UwJZWkZ8
The first drop-down menu for prepocessing the text only shows "None".

**Comment by ajdapretnar** [comment]
Ah, ok. I think the NLTK data didn't load correctly. Would you be able to run Orange from the console with `python -m Orange.canvas -l 4` and post the output?

@nikicc Do you have any idea, why NLTK isn't imported in the widget?

**Comment by ftastisch** [comment]
In the pyhton shell?
>>> python -m Orange.canvas -l 4

**Comment by nikicc** [comment]
> @nikicc Do you have any idea, why NLTK isn't imported in the widget?

Not really to be honest. But it sounds like that the files didn't load correctly.

@ftastisch did you manage to run Orange with `python -m Orange.canvas -l 4`? This command runs Orange but will also print quite some logs to the console. It would be very helpful if you could paste the output here, so we can try to figure out what is going on.

**Comment by fotastisch** [comment]
Hi!
Sorry, I had problems accessing my account.
It seems that python is not installed correctly (I used the miniconda version at first and then anaconda), so I will try to move to a "real" python installation and check whether this solves the problem.

**Comment by nikicc** [comment]
> It seems that python is not installed correctly (I used the miniconda version at first and then anaconda), so I will try to move to a "real" python installation and check whether this solves the problem.

If you installed it through Anaconda, make sure to that you are using it's Python. To do this, activate the anaconda environment and then run the `python -m Orange.canvas -l 4` there. If you can run Orange, then I assume everything is OK with Python and perhaps you are just no using the correct one.

**Comment by kafran** [comment]
I can't see Stopwords from NLTK either. I tryied everything I know to solve this. Do you know if it's needed to export nltk_data variable?

**Comment by kafran** [comment]
Yep. This is true. You have to export NLTK_DATA.
$ export NLTK_DATA=/home/[user]/.local/share/Orange/nltk_data
replace [user] with your username.

Does anybody knows how to make this permanent?

**Comment by ajdapretnar** [comment]
This was a frequent issue at our latest workshop. Most people installed Orange from the installer on Windows (with Miniconda), but did not see any of preinstalled packages.

**Comment by ajdapretnar** [comment]
I have tested this on Windows 10, recommended Miniconda installer, installed add-on from Options-Add-ons.
NLTK_DATA resources are not shown.
They are however downloaded to: /Users/user/AppData/Roaming/Orange.

**Comment by kernc** [comment]
Interesting. They should be downloaded into  \\Users\\user\\AppData\\Roaming\\Orange\\[nltk_data](https://github.com/biolab/orange3-text/blob/e8b34d1d3fab2dde2a78ed6e737b652d2740f1ea/orangecontrib/text/misc/nltk_data_download.py#L25) by us by [either](https://github.com/biolab/orange3-text/blob/13bb87cb9ff89e62bfcb55bc0ff9a869e4a3e032/orangecontrib/text/__init__.py#L4) method.

If https://github.com/biolab/orange3-text/issues/331#issuecomment-377652442 describes a workaround, perhaps the env variable needs to be set earlier.

**Comment by ajdapretnar** [comment]
Yes, they are downloaded and not broken (I tested them). They are just not recognized by Orange. 🤔 So if I just set env before everything else, it should work?

**Comment by ajdapretnar** [comment]
Fixed in #355.
