### ISSUE TITLE
Select column missing a column after sentiment analysis

### ISSUE THREAD

**Issue by ghltshubh** [biolab/orange3-text#332]
##### Text version

0.3.0

##### Orange version

3.8.0

##### Expected behavior
Contain column named "compound'

##### Actual behavior
Missing column named "compound"

##### Steps to reproduce the behavior
Corpus -> import election_tweets dataset -> sentiment analysis -> Data Table -> select columns

**Comment by ajdapretnar** [comment]
Could you perhaps provide a screenshot of the workflow as well?

**Comment by ajdapretnar** [comment]
Closed due to inactivity. Once the problem is better described, we can reopen.
Anyway, looking at this one more time it could be that you simply haven't selected anything in a Data Table.
