### ISSUE TITLE
Preprocess Text unable to browse files without ".txt" extension

### ISSUE THREAD

**Issue by chasets** [biolab/orange3-text#333]
##### Text version
0.3.0

##### Orange version
3.8.0

#### Additional version information
MacOS 10.12.6
Conda 4.3.29
Python 3.6.0

##### Expected behavior
In the Preprocess Text widget, the user should be able to choose the folder icon for "Stopwords" or "Lexicon" and browse to a file containing the appropriate text, regardless of the name of the file. This is especially true considering that the included nltk files do not conform to a ".txt" convention. 

##### Actual behavior
The File Chooser only allows selection of files with the ".txt" extension as part of the filename. The files included with orange3-text at nltk_data/corpora/stopwords/* do not include this extension, so they are not available to choose in Preprocess Text. 

##### Steps to reproduce the behavior
1. Add a Corpus widget and choose book-excerpts.tab
2. Connect a Preprocess Text widget
3. Open the Preprocess Text widget and browse to the nltk_data/corpora/stopwords directory
4. None of the files here are available for selection
5. In the OS, rename the file named "english" to "english.txt"
6. Repeat step 3 above
7. The file "english.txt" is available to choose for stopwords

##### Additional info (worksheets, data, screenshots, ...)
![orange_preprocess_text_screenshot](https://user-images.githubusercontent.com/7545948/35393617-7ccfe93a-01b3-11e8-836b-7df1e8b94862.jpg)

**Comment by kernc** [comment]
Thanks for the report. Would you like to try submitting a patch fixing the issue?

**Comment by chasets** [comment]
Sure, I'll give it a shot. I have the fix, now I just need to figure out
the submission process.

**Comment by kernc** [comment]
Any sort of diff patch is fine, but easiest to review and apply would be a pull request here on GitHub. This is the [basic workflow](https://guides.github.com/introduction/flow/):
1. Create a local fork of the repository (Fork button on the top right).
2. Apply changes on a [topic branch](https://guides.github.com/activities/forking/) of _your_ repository.
3. Propose changes as a pull request to this repository.

Here's [some commands](https://github.com/PointCloudLibrary/pcl/wiki/A-step-by-step-guide-on-preparing-and-submitting-a-pull-request) to go with it. Don't avoid asking if you need help.

**Comment by chasets** [comment]
Done. I'll await comments at https://github.com/biolab/orange3-text/pull/334

--Tim
