### ISSUE TITLE
Tokenization: Mysterious empty space appears

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-text#335]
##### Text version

0.3.0

##### Orange version

3.10.dev

##### Expected behavior
When tokenizing, I don't get an empty token.

##### Actual behavior
I get an empty token using default Regex and Tweet tokenizers.

##### Additional info (worksheets, data, screenshots, ...)
See the first token. It is also listed in Word Cloud.

<img width="612" alt="screen shot 2018-02-05 at 11 41 00" src="https://user-images.githubusercontent.com/12524972/35800588-b2a79ada-0a69-11e8-9ef1-d3fc24814e16.png">

**Comment by matejklemen** [comment]
Hey, is this still a problem? I can't seem to be able to reproduce the issue (and I realize it's quite an old one). If it is, could you please provide steps to reproduce the behavior?

**Comment by ajdapretnar** [comment]
Yes, I can't reproduce this either.
