### ISSUE TITLE
requirements.txt contains the wrong version of pdfminer3k

### ISSUE THREAD

**Issue by yurivict** [biolab/orange3-text#343]
It has ```pdfminer3k>=1.3.1```.
The PyPI page has the version 20110515: https://pypi.org/project/pdfminer3k/
And the corresponding GitHub project has the version 1.2.4: https://github.com/jaepil/pdfminer3k/releases

**Comment by kernc** [comment]
Version [1.3.1](https://pypi.org/project/pdfminer3k/1.3.1/) was the updated version @hsoft was working on, but which has since been replaced/downgraded back to 20110515 version.

**Comment by ajdapretnar** [comment]
@kernc Can this be closed then? I don't know what the true issue is. Does something not work?

**Comment by kernc** [comment]
The issue is we are depending on a specific version of a project that has since been unpublished (or at least officially superseded by a prior, more bug-ridden version) and abandoned. If we consider those an issue at all.

**Comment by ajdapretnar** [comment]
I see. That's a bugger. From what I know, only Import Documents uses pdfminer and it seems to work.
I have tested this on Windows (fresh installation) and reading pdfs seems to work just fine (and if it works on Win, it works everywhere). I would not consider this an issue.
