### ISSUE TITLE
The dependency 'typing' should be only for python versions <3.5

### ISSUE THREAD

**Issue by yurivict** [biolab/orange3-text#344]
According to documentation https://docs.python.org/3/library/typing.html , 'typing' is in the base python distribution since 3.5.

'typing' can be excluded packages beginning from python-3.5, so yo can't just declare it as a general dependency.

**Comment by kernc** [comment]
Agreed.

Would you like to help out by doing a PR?

**Comment by yurivict** [comment]
https://github.com/biolab/orange3-text/pull/346
