### ISSUE TITLE
preprocess.py does not check for type of data in stopword list

### ISSUE THREAD

**Issue by nitishjain2007** [biolab/orange3-text#35]
While checking for stopwords, it may be possible that the list contains some non-string type entries.

**Comment by nitishjain2007** [comment]
A solution to this might be checking the list contents and verifying their types.

**Comment by nikicc** [comment]
I agree. We are working on a major redesign of preprocess (#21) and will incorporate this.
@david-novak  could you add this to PR #21?

**Comment by kernc** [comment]
What other types are expected in the input list?

**Comment by nikicc** [comment]
I think only strings are expected and meaningful and that Nitish just propose a sanity check.

**Comment by david-novak** [comment]
@nikicc Noted, will include this in the next update.

**Comment by nikicc** [comment]
This is fixed in the new preprocessing.
