### ISSUE TITLE
Guardian: Fix failing tests on Travis

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-text#354]
##### Text version

0.3.0

##### Orange version

3.15.dev

##### Expected behavior
Tests pass.

##### Actual behavior
Guardian tests is failing.

##### Additional info (worksheets, data, screenshots, ...)
Fix tests.

**Comment by ajdapretnar** [comment]
Issue is with invalid credentials. I am not sure whether to turn off tests for Guardian or we can somehow set test credentials.

**Comment by robertcv** [comment]
The tests are failing due to the limit on the "test" key. The best solution would be to contact them to get a key with a higher limit. According to the [documentation](https://open-platform.theguardian.com/documentation) under Polling guide, this is something they are willing to do.

**Comment by kernc** [comment]
https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings
