### ISSUE TITLE
Corpus Viewer: Doesn't show Instagram images

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-text#373]
##### Text version

0.4.0

##### Orange version

3.16.dev

##### Expected behavior
Corpus Viewer used to show Instagram images.

##### Actual behavior
There is only an icon, showing the widget cannot display any photos.

##### Steps to reproduce the behavior
Ask for data set.

##### Additional info (worksheets, data, screenshots, ...)
<img width="268" alt="screen shot 2018-09-04 at 14 50 43" src="https://user-images.githubusercontent.com/12524972/45032363-ea078100-b051-11e8-85c5-9d8a320b78aa.png">

**Comment by ajdapretnar** [comment]
Probably related to Instagram API. Could be this cannot be fixed.

**Comment by robertcv** [comment]
I tested Corpus Viewer on my data and it works normally. Please check if the URL-s in your dataset are ok.
