### ISSUE TITLE
Word Cloud: don't update on resize

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-text#390]
##### Text version

0.5.2

##### Orange version

3.17.dev

##### Expected behavior
Word Cloud stays the same for the same domain.

##### Actual behavior
WC constantly changes. WC should not update on resize. It should also show constant colours for users.

**Comment by robertcv** [comment]
This problem is due to drawing the words with a third party javascript library. To fix this and other related problems with word cloud a reimplementation with qt is necessary. As this isn't planned for the near feuter, i will close this issue.
