### ISSUE TITLE
Error importing PDFDocument

### ISSUE THREAD

**Issue by PrimozGodec** [biolab/orange3-text#396]
##### Orange version
Orange 3.18. Installed using pip (Python 3.5) on Ubuntu 16.04

##### Error
Error while importing 'orangecontrib.text.widgets.owimportdocuments'. The widget will not be shown.
......
......
......
from pdfminer.pdfparser import PDFParser, PDFDocument
ImportError: cannot import name 'PDFDocument'

##### Steps to reproduce the behavior
Start the application in terminal using orange-canvas

##### Additional info - Resolution
from pdfminer.pdfdocument import PDFDocument

**Comment by PrimozGodec** [comment]
Not an error. Solved.

**Comment by kodymoodley** [comment]
I am also getting this error.

Versions:
---------

PyQt5==5.15.7
PyQtWebEngine==5.15.6
Orange3==3.34.1
Orange3-Text==1.12.0
Orange3-network==1.7.0

MacOSX Ventura 13.1 (M1 chip)
