### ISSUE TITLE
Maps not properly sized in some cases

### ISSUE THREAD

**Issue by kernc** [biolab/orange3-text#4]
Some users get

![geomap](https://cloud.githubusercontent.com/assets/684364/8672710/4290e938-2a31-11e5-88ed-aac5fd26a36c.png)
![geomap](https://cloud.githubusercontent.com/assets/684364/8672721/5ae99bec-2a31-11e5-9441-5166337bc06b.png)

> pognal owgeomap.py file: pokaze svet raztegnjen cez celo sirino okna (visina ni cela), ce zamenjam na europe dobim majhno slikico, po resize-u okna se malo izboljsa (slika 2).

Qt* version likely not culprit.

cc: @BlazZupan @lanzagar

**Comment by kernc** [comment]
@lanzagar does legend ever render correctly?
![legend](https://cloud.githubusercontent.com/assets/684364/8672859/653a4e6a-2a32-11e5-9e10-447d466327fd.png)

**Comment by lanzagar** [comment]
The legend never renders correctly.
One error:
Failed to load resource: Request for opening non-local file file://orangecontrib/text/widgets/resources/jquery-jvectormap-2.0.2.css

**Comment by ajdapretnar** [comment]
For me, the problem persists:

![geomap1](https://cloud.githubusercontent.com/assets/12524972/14106411/45777cf6-f5b1-11e5-8c5d-aa453d17ce84.png)
