### ISSUE TITLE
i don't see in Preprocess Text

### ISSUE THREAD

**Issue by malgm21** [biolab/orange3-text#400]
##### Orange version
3.18

##### Expected behavior
preprocess text

##### Actual behavior
i don't see Preprocess Text

##### Steps to reproduce the behavior
![preprocess text](https://user-images.githubusercontent.com/45428980/49160682-a54a6800-f36a-11e8-9881-19d90879d1bf.png)

**Comment by ajdapretnar** [comment]
Could you please tell us how you installed the add-on and Orange?

**Comment by ajdapretnar** [comment]
Closed due to inactivity.
