### ISSUE TITLE
Corpus Viewer: filtering non-ASCII signs in filenames

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-text#402]
##### Text version

0.5.2

##### Orange version

3.19.0

##### Expected behavior
Corpus Viewer can filter by any Unicode characters, even when read from local files.

##### Actual behavior
Corpus Viewer can't match č, ž, š when those letters come from file names.

##### Steps to reproduce the behavior
Import Documents (read some files with č, š, ž in their names) and then use Corpus Viewer to filter them. Filtering works fine for Content.

##### Additional info (worksheets, data, screenshots, ...)
<img width="497" alt="screen shot 2018-12-03 at 16 07 12" src="https://user-images.githubusercontent.com/12524972/49381983-8276d580-f715-11e8-87d2-73aae091c188.png">
<img width="497" alt="screen shot 2018-12-03 at 16 07 04" src="https://user-images.githubusercontent.com/12524972/49381989-89054d00-f715-11e8-9aa4-1f3caff4d04f.png">

**Comment by robertcv** [comment]
This issue was related to strange characters in the filename.
