### ISSUE TITLE
[ENH] github support

### ISSUE THREAD

**Issue by gramster** [biolab/orange3-text#404]
I might do this myself if there is good documentation on how to add new data sources. Is there?

API: https://developer.github.com/v3/

**Comment by ajdapretnar** [comment]
I do not understand this issue. Please elaborate.

**Comment by robertcv** [comment]
Hey! You would probably like to do text analysis on issues, pull request, repository descriptions, ... There is no documentation on how to add new sources. You would need to implement a new widget for searching through the GitHub API. The Guardian widget would be a good starting point for how to do so. You can find its code in [guardian.py](https://github.com/biolab/orange3-text/blob/master/orangecontrib/text/guardian.py) and [owguardian.py](https://github.com/biolab/orange3-text/blob/master/orangecontrib/text/widgets/owguardian.py).

**Comment by ajdapretnar** [comment]
I am closing this as there are no core developers that would handle this task in the near future. Feel free to add you own widget that implements the API. We are glad to comment on the PR.
