### ISSUE TITLE
[ENH] Present Preprocessor output

### ISSUE THREAD

**Issue by TheNewSound** [biolab/orange3-text#405]
Please let preprocessor-text present a Prepocessor output so it can be applied to cells/columns in a orange table.

![image](https://user-images.githubusercontent.com/1410503/50782159-8fa05a80-12a7-11e9-8331-ebda4f12b2e9.png)

**Comment by ajdapretnar** [comment]
Preprocess Text does not implement a preprocessor, but a preprocessing text pipeline. It modifies a property self.tokens, so it cannot be used in the same way as Preprocessor output in core Orange. But I know what you wish to achieve - run the same preprocessing pipeline on new data. We will think about how to do that.

**Comment by ajdapretnar** [comment]
This can already be achieved with Preprocess Text. Turn on the n-gram part and set it to 2-2 (to have only bi-grams without one-grams). That said, the downside of this is that the pipeline is fixed, so each step is executed in the sequence you see (you can't filter n-grams, for example). Then run Bag of Words, Distances and voila, you have a distance matrix right there.

<img width="533" alt="screen shot 2019-01-07 at 18 33 20" src="https://user-images.githubusercontent.com/12524972/50783310-bdd36980-12aa-11e9-8aab-8abc608f1131.png">

**Comment by TheNewSound** [comment]
Wow nice! Thanks alot! One more question: I would like to get the sorensen-dice distance.

The sorensen-dice distance is 2 times the length of the intersection of the 2 collections divided by the sum of the collections lengths. How would I need to configure the components?

example with the following collections:
```
ZZ ZX XX XZ ZX XX
ZA AX XX XZ ZX XX XA
```
intersection should be 4*2=8, union should be 6+7=13

**Comment by ajdapretnar** [comment]
You could potentially implement at new distance metric in Distances. I cannot think of another way.

**Comment by ajdapretnar** [comment]
I am closing this as Preprocess Text (and other widgets) can be duplicated with Ctrl+C, Ctrl+V. Not ideal, but so far a good way to reproduce the results for prediction and alike.
