### ISSUE TITLE
Error with prediction widget for latest version of orange

### ISSUE THREAD

**Issue by hpchew1** [biolab/orange3-text#415]
Predictions widget have error in t
![predictions error](https://user-images.githubusercontent.com/47921012/53287587-2c1baf00-37b9-11e9-966b-bd1e99c5e8df.PNG)
he latest version of orange. Error attached.

**Comment by ajdapretnar** [comment]
This is not an issue for Text add-on. Please report this to the [core Orange](https://github.com/biolab/orange3/issues) repository and please add the workflow that reproduces the issue. Thank you!
