### ISSUE TITLE
Preprocess Documentation

### ISSUE THREAD

**Issue by cheral** [biolab/orange3-text#42]
@nikicc 

The documentation for the preprocess widget in orange-text is same as that of the preprocess widget in orange under the data section in the toolbox bar
https://github.com/biolab/orange3-text/tree/master/doc/widgets

Shall I update the rst file for preprocess in orange text or is there any plan to add more features in preprocess ?

**Comment by nikicc** [comment]
@cheral: A major redesign of the of the preprocessing code for Orange3-Text is coming with PR #21, so I believe now is not the right time for updating documentation. Can we please wait for #21 to be accepted and fix the documentation then?

**Comment by cheral** [comment]
Sure !!
How can I contribute for  redesign of the preprocessing code?
Any other widget in Orange3-Text that you think has to be redesigned and I can contribute?

**Comment by nikicc** [comment]
Preprocessing is more or less done, we just need some minor fixes, but David is already working on this. I would also suggest, as Ajda already said on google groups, to focus on the project proposal for now. But if you are really eager to write a widget, you can try do write one of those that you are proposing in your project.

**Comment by nikicc** [comment]
We have a bit more documentation for preprocessing. @cheral do you agree to close this issue?

**Comment by cheral** [comment]
Yes

**Comment by cheral** [comment]
@nikicc  , we need to reopen it. Preprocess still opens with the old documentation of the orange3 preprocess widget
![image](https://cloud.githubusercontent.com/assets/9462412/15736706/29588ac4-28bf-11e6-8771-4d5d783be00e.png)
even I couldn't link article scraper documentation with the widget

**Comment by ajdapretnar** [comment]
@nikicc That's true. We've got to fix this. :disappointed:

**Comment by ajdapretnar** [comment]
Fixed in https://github.com/biolab/orange3/pull/1307.
