### ISSUE TITLE
Saving a tab file after using 'import documents widget'

### ISSUE THREAD

**Issue by lawrencerowland** [biolab/orange3-text#426]
##### Text version

0.6.0

##### Orange version

3.20.1 on Mac. 

##### Expected behavior
"Import documents to create corpus". Send corpus to 'Save file", using *.tab format, to save the results in a folder. Using Corpus widget, can open this new tab file, with text features listed below. 

##### Actual behavior
Import is successful and I can use the corpus in workflows.
But if I try to open the new tab file as a Corpus, then I get:
-Two error messages: "Corpus doesn't have any text features"
-Error message: "Can't read file ... line contains NULL byte"

##### Steps to reproduce the behavior
I have tried:
1. opening corpus in new orange session
2. saving corpus as *.csv or .xlsx
3. trying different folders for import documents
4. opening tab file first as folder and then linking it to a Corpus widget
5. inspecting *.tab file in text editor or excel for errors.
6. trying the same versions in Windows as well as Mac

##### Additional info (worksheets, data, screenshots, ...)
The idea is to avoid having to start each session with importing documents, by starting from a tab file

**Comment by ajdapretnar** [comment]
I have tried this and it works fine for me.
Do you perhaps have some minimal dataset that you can share so we can test it?

**Comment by lawrencerowland** [comment]
Hi, thanks for having a look at this. 
I have cut it down to a small dataset of five documents, where the error replicates. 
One potential work-around though - if I save it as a pickle file then it will re-open it with the Corpus widget. corpus for replicating failed tab text file.zip

**Comment by lawrencerowland** [comment]
[corpus for replicating failed tab text file.zip](https://github.com/biolab/orange3-text/files/3112902/corpus.for.replicating.failed.tab.text.file.zip)
sorry, it didn't upload the first time

**Comment by ajdapretnar** [comment]
@lawrencerowland You a right. Now I can replicate this. I assume it is because of the faulty pdf (2009 Prioritisation by WSTF Weighted Shortest skimmed interesting). Still, Import Documents should probably handle this while importing. We will have a look.
