### ISSUE TITLE
Twitter Widget does not commit search on open workflow

### ISSUE THREAD

**Issue by mfiguerc** [biolab/orange3-text#427]
Unfortunately, the Orange Twitter widget does not automatically commit  the search when opening the model. It could be useful to automate the Workflow each time it is open with scheduled task

**Comment by ajdapretnar** [comment]
This would require some redesign of the widget. Currently, if Search is pressed on an empty query word list, the widget returns random selection of tweets. Auto-commit would have to consider this so the widget doesn't run every time it is initialized.

I am also not sure we'd like to have auto-commit. This would stall the workflow a lot when no limitation is given. Even File widget prohibits auto-loading of big data sets. I am leaning towards a wontfix. I think programmatic approach is much more appropriate for this task, but I am open to discussion.

**Comment by ajdapretnar** [comment]
Upon some discussion, I think this is a wontfix. I suggest using Twitter API programmatically.
