### ISSUE TITLE
In Twitter widget does not appear query time frame fields

### ISSUE THREAD

**Issue by mfiguerc** [biolab/orange3-text#428]
I have the last version of Orange 3.2 and text analysis Add-on 6.0 but in the Twitter widget does not appear the fields to set the query time frame.

**Comment by ajdapretnar** [comment]
Yes, this is correct. Twitter API only ever gives tweets from the past two weeks, so time frames are effectively useless.

**Comment by mfiguerc** [comment]
OK but I meant that in the Twitter widget user interface the two fields do not appear how is shown in the documentation

**Comment by ajdapretnar** [comment]
I know, I know. I will fix the documentation asap. I apologize for this.
