### ISSUE TITLE
Unable to install the "Text" addon

### ISSUE THREAD

**Issue by raindropsfromsky** [biolab/orange3-text#430]
This is in continuation with issue #422.

The issue was closed with the resolution that the user must install anaconda version.
Well, the miniconda version is there only for 64-bit systems. But I have a 32-bit system, and so I have to use the classic installer of Orange, which does NOT have anaconda.

However, I am unable to re-open the bug.
That is why I have to open a separate bug here.

The classic (32-bit) Orange installer does not have miniconda component at at all.
Instead, the installer installs Python 3.6.5 (32-bit), which cannot be skipped.

But since the bug #422 was closed with the remarks that we should use miniconda, I downloaded a separate vanilla version of miniconda for 32-bit. It installs Python 3.7.x.

However, when I try to install the **Text** addon, Orange launches the built-in version of Python (v 3.6.5) only, not the Python contained in miniconda (3.7.x).

This shows that I have taken all possible steps, yet unable to use Orange 3 for Text mining.
This is a huge problem, and should be resolved.

Just to avoid any doubts, I first removed Orange, miniconda and all Python versions installed on my PC, and restarted the PC. Then I installed miniconda using  the "Install as administrator" option. Then I restarted the PC again. Finally I installed Orange using  the "Install as administrator" option. 

Again I restarted the PC, so that Orange can find the miniconda PATH.

But this extreme precaution does not give me any good result.
*****
BTW the Windows [installation page](http://orange.biolab.si/download/windows/) has some instruction in the "Anaconda" heading. They mention how to use specific channels to find packages from. I wonder if this text is meant for Linux users, because I have never used "Channels" and "packages" for any Windows-based installations.

IMHO the instruction should be shifted to Linux installation page.

**Comment by ajdapretnar** [comment]
Lots of issues here.

1. Orange creates a separate environment that uses the downloaded Python (3.6.5). Your 32-bit Miniconda is not recognized by Orange. If you are installing with vanilla Miniconda, you need to follow the [Anaconda instructions](https://github.com/biolab/orange3#installing). Then you should also install Orange3-Text the same way - `conda install orange3-text`.

2. It is possible Orange3-Text won't work on 32-bit systems because if its dependencies. Not something we can solve, really.

3. Instructions of installing with Anaconda are completely correct and apply to most OS systems (Win, OSX and Linux). This relates to 1. You should follow these instructions when installing with Anaconda.

**Comment by raindropsfromsky** [comment]
This is getting incredibly complex for a typical Windows user who does not have such coding/scripting knowledge or skills. 

Instead of focusing on the text-mining, we are getting stuck in the endless loop of miniconda, anaconda, 
and Python.

IMHO this should work with a single installer. Why should we need such scripting skills??

**Comment by raindropsfromsky** [comment]
Further to that, I tried to install Anaconda (well, I already have miniconda, but now the article is asking for Anaconda, so I have to get it).

First step, to follow the [link](https://www.continuum.io/downloads). It is not working!
The connection timed out (Error 522).

**Comment by raindropsfromsky** [comment]
On Googling further, I found this [site](https://www.anaconda.com/distribution/#download-section) for downloading Anaconda. But all the downloads are for 64-bit versions only.

**Comment by ajdapretnar** [comment]
Well, then it is not possible to use Text for 32-bit version, as I have mentioned earlier.

**Comment by franklonnelly** [comment]
Hi, I have got a 64-bit Windows 10 but I could not install the adds-on Text Mining on Orange 3.20. The error has no number and just says "python pip install Orange3-text exited with non zero status"

**Comment by ajdapretnar** [comment]
This is a separate issue. Please open a new issue and describe how you installed Orange and the add-on.
