### ISSUE TITLE
Corpus: enable setting the target variable

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-text#454]
This is up for discussion. Currently, it is not possible to set a target variable in Corpus nor can one edit variable types.

This can be achieved by first loading the data in File widget and then passing it to Corpus. Is that ideal? I don't know.

Would we want to add similar functionality to Corpus widget or not?

**Comment by ajdapretnar** [comment]
I guess we decided against it.

**Comment by gengyabc** [comment]
Then how can we know which one is the target. I found the example workflows use logistic regression to predict, but what is the target, why the target is that?
