### ISSUE TITLE
Preprocess text widget should remove stop-words

### ISSUE THREAD

**Issue by PrimozGodec** [biolab/orange3-text#455]
##### Text version

0.7.3dev

##### Orange version

3.24.0dev

##### Expected behavior

- Preprocess text widget should remove stop-words from the text for the Slovene language.
- Stopwords languages should be ordered in alphabetical order.

##### Actual behavior

It does not happen when stopwords from NLTK are used - the problem is spaces beside the stopwords.

##### Steps to reproduce the behavior

Read some data with Import documents and connect with Preprocess Text widget. Observe the output of Preprocess Text widget.

**Comment by ajdapretnar** [comment]
@PrimozGodec So in essence NLTK has the wrong stopwords? 😱

**Comment by PrimozGodec** [comment]
I opened the issue on NLTK https://github.com/nltk/nltk_data/issues/139, anyway I think #456 can be a quick fix. I think it is an OK solution since it is linear.
