### ISSUE TITLE
Save model not working with Text Normalization (Preprocess Text widget)

### ISSUE THREAD

**Issue by CrtGrahonja** [biolab/orange3-text#466]
##### Text version
Orange3-Text 0.7.3

##### Orange version
Orange 3.23.1

##### Expected behavior
Saves a preprocessed and trained model to a pickle file.

##### Actual behavior
Raises an error, because it tries to pickle udpipe.Model

##### Steps to reproduce the behavior
 * Load a Corpus with a target variable,
 * Preprocess using **UDPipe Lemmatizer** (tried English and Slovene, both failed),
 ** _when not using UDPipe Lemmatizer, the saving works!_
 * use BoW,
 * model (any),
 * Save Model.

##### Additional info (worksheets, data, screenshots, ...)
Screenshot of my workspace and error
![image](https://user-images.githubusercontent.com/39695964/67549289-2ee1f180-f704-11e9-95bf-2ba9ec7bf1ee.png)

Screenshot of my Preprocess Text widget
![image](https://user-images.githubusercontent.com/39695964/67577872-9ec29d00-f741-11e9-947a-01f58429bfc9.png)

**Comment by ajdapretnar** [comment]
This should be fix in the latest release via #447. Please update and check if it works.
