### ISSUE TITLE
Save tokenized output to data file?

### ISSUE THREAD

**Issue by JamesBuell** [biolab/orange3-text#477]
##### Expected behavior
I'm new to Orange3 and the orange3-text addon. In fact, I just installed both last night on MacOS Mojave using the bundled .dmg from https://orange.biolab.si/download/#macos.

I'm figuring out how to bring in a folder's texts with the Import Documents widget, use the Preprocess Text widget to tokenize sets of text files as sentences (radio button selection), and to display those sentences in the system using Corpus Viewer (checkbox for 'Show tokens and tags'). Happily, the Corpus Viewer shows this:

![image](https://user-images.githubusercontent.com/16169040/69746013-fe2d1780-1108-11ea-8d4f-e30e429faedc.png)

I'd like to output the sentences the tokenizer produces, to a .tab or .csv file. My first thought was to connect Corpus Viewer to an instance of the Save Data widget.

![image](https://user-images.githubusercontent.com/16169040/69739360-329ad680-10fd-11ea-9583-ff68c0b9619a.png)

##### Actual behavior
However, the .tab file created by Save Data does not break out the text using the sentence tokens that display in Corpus Viewer. The file's rows evidently come from the original texts that were brought in with Import Documents, and so appear like this:

![image](https://user-images.githubusercontent.com/16169040/69746105-32083d00-1109-11ea-80a6-32ee1dec03cf.png)

Might there be some way to create a workflow that would lead to creating a .tab file whose rows are the individual sentence tokens that the Corpus Viewer widget displays onscreen?

If this isn't possible with Orange3 and orange3-text, could someone suggest a Python shell script that could achieve the same sort of result, using NLTK or a similar library from the command line?

Thanks,
Jim

**Comment by ajdapretnar** [comment]
Hi Jim!

I've prepared a Python Script for you.
[sentences-to-corpus.py.zip](https://github.com/biolab/orange3-text/files/3901122/sentences-to-corpus.py.zip)

You can use it quite simply. The script will use each token as a new document. A document will also have the original 'Title', to keep the information on the source. The script assumes you have the Title column in your data.
<img width="527" alt="Screen Shot 2019-11-28 at 11 22 39" src="https://user-images.githubusercontent.com/12524972/69798357-7101c580-11d1-11ea-976c-65c36481a44f.png">

The output of the script is a new corpus, which you can use just like you would a regular corpus in Orange.

For the end, a little explanation: tokens are a hidden property of Corpus. They are used for creating the bag of words, word cloud, in topic modeling, and elsewhere, but they are passed around silently. The script uses the token property to create a new corpus.

**Comment by JamesBuell** [comment]
Thanks Ajda! The script does just what I was looking for. 

I hadn't even realized til you posted that Orange has a Python Script widget. I've just now located your page introducing it, 'Python Script: Managing Data on the Fly', at https://orange.biolab.si/blog/2018/05/15/python-script-managing-data-on-the-fly/. Also looking over the doc at https://docs.biolab.si//3/visual-programming/widgets/data/pythonscript.html -- particularly the final example there on that page, which uses Orange3-Text add-on.

**Comment by jaro1504** [comment]
Hi. I am very new to using Orange and using the text-addon. Refering to the above script. Is it possible to export tokens and tags, when the input text is tokenized not as sentence (as in the above example), but tokenized into single words, with inputing "whitespace"? Thank yo
[github.pdf](https://github.com/biolab/orange3-text/files/7548161/github.pdf)
u.

**Comment by ajdapretnar** [comment]
@jaro1504 If I understand you want something like this?
|  Docs  |  Tokens   |
|---|---|
|  Doc1  |  we should improv this  |
|  Doc2  |  we should do something else  |
|  Doc3  |  something else entirely  | 

You could only do it with a Python Script widget.
Something along the lines of:
```
from Orange.data import StringVariable

out_data = in_data.copy()
var = StringVariable("tokens")
new_var = [" ".join(doc) for doc in in_data.tokens]
out_data = out_data.add_column(var, new_var)
```

**Comment by jaro1504** [comment]
Thank you very much for your help. This is exactly how I would like to do it.

**Comment by NAsic123** [comment]
> 

@ajdapretnar do you know how to import exactly the same output from Orange to R Studio?

**Comment by ajdapretnar** [comment]
> How to save the data from Orange to R Studio?

Please see the FAQ: How to save the data from Orange to R Studio?

**Comment by Air51** [comment]
> @jaro1504 If I understand you want something like this?
> Docs 	Tokens
> Doc1 	we should improv this
> Doc2 	we should do something else
> Doc3 	something else entirely
> 
> You could only do it with a Python Script widget. Something along the lines of:
> 
> ```
> from Orange.data import StringVariable
> 
> out_data = in_data.copy()
> var = StringVariable("tokens")
> new_var = [" ".join(doc) for doc in in_data.tokens]
> out_data = out_data.add_column(var, new_var)
> ```

Thank you, bro!!!!!
