### ISSUE TITLE
Better filtering in concordance widget

### ISSUE THREAD

**Issue by PrimozGodec** [biolab/orange3-text#480]
##### Text version
0.7.4

##### Expected behavior

When we get a query word from another widget (e.g. word cloud), it can be normalized and not in the original form anymore. When concordance is used, we would expect to get all appearances of this word before the normalization. 

##### Actual behavior

 For words that have been normalized by the preprocess widget, we cannot get their context with the concordance widget. I had an example where I wanted to see the concordance of a word that was most frequently appearing in the text. The concordance widget did not show anything since the word was changed with the normalization. I know it is a difficult task to match tokens with real text, so the real appearance would be hard to get, but we can try to make some partial matching. We should show words that contain a query text since normally normalized word would be contained in its non-normalized form.
It is not a perfect solution, but I believe it is a better solution.

**Comment by ajdapretnar** [comment]
Duplicate of https://github.com/biolab/orange3-text/issues/320.

**Comment by PrimozGodec** [comment]
Sorry, closing the issue.
