### ISSUE TITLE
Topic Modeling: LDA in Orange different than the one from gensim

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-text#484]
##### Text version

0.7.5

##### Orange version

3.24.dev

##### Expected behavior
```
import pandas as pd
from gensim.corpora import Dictionary
from gensim.models.ldamodel import LdaModel

df = pd.read_csv('book-excerpts.csv')
tokens = [[word for word in document.lower().split()] for document in df['Text']]

dictionary = Dictionary(tokens)
corpus = [dictionary.doc2bow(doc) for doc in tokens]

lda = LdaModel(corpus, 10)
for index, topic in lda.show_topics(formatted=False, num_words=10):
    print('Topic: {} \nWords: {}'.format(index, [dictionary[int(w[0])] for w in topic]))

Topic: 0 
Words: ['the', 'of', 'and', 'to', 'a', 'in', 'i', 'it', 'was', 'that']
Topic: 1 
Words: ['the', 'and', 'i', 'of', 'to', 'a', 'in', 'that', 'you', 'with']
Topic: 2 
Words: ['the', 'and', 'of', 'to', 'a', 'in', 'it', 'was', 'that', 'i']
Topic: 3 
Words: ['the', 'and', 'of', 'to', 'a', 'i', 'in', 'was', 'he', 'as']
Topic: 4 
Words: ['the', 'and', 'a', 'to', 'i', 'of', 'in', 'was', 'that', 'she']
Topic: 5 
Words: ['the', 'and', 'a', 'of', 'to', 'in', 'i', 'was', 'you', 'her']
Topic: 6 
Words: ['the', 'and', 'to', 'i', 'of', 'a', 'in', 'it', 'that', 'as']
Topic: 7 
Words: ['the', 'and', 'i', 'to', 'of', 'a', 'in', 'was', 'that', 'my']
Topic: 8 
Words: ['the', 'and', 'of', 'to', 'a', 'her', 'i', 'that', 'in', 'was']
Topic: 9 
Words: ['the', 'and', 'of', 'i', 'to', 'a', 'was', 'her', 'in', 'that']
```

##### Actual behavior
Book excerpts corpus without any preprocessing.

<img width="939" alt="Screen Shot 2019-12-12 at 14 32 40" src="https://user-images.githubusercontent.com/12524972/70716285-5741a180-1cec-11ea-941d-b547132702e0.png">

##### Additional info (worksheets, data, screenshots, ...)
Test data: 
[book-excerpts.csv.zip](https://github.com/biolab/orange3-text/files/3955981/book-excerpts.csv.zip)

1. Why do these two outputs differ? I assume it is preprocessing, but I cannot find where this happens in Orange.
2. Why does Orange show all zero topics?

**Comment by robertcv** [comment]
The difference seems to be from how the model is fitted. In Orange, the `LdaModel` is fitted iteratively with the update method, so that we can show the progress.

**Comment by ajdapretnar** [comment]
@robertcv Thanks, at least we know why this happens. I am still a bit skeptical whether it is ok to iteratively update the model. 🤔 I dunno. Perhaps it is.
