### ISSUE TITLE
Andaconda Install Addon Issue

### ISSUE THREAD

**Issue by EsotericRebel** [biolab/orange3-text#485]
##### Expected behavior

Install addon for text for latest Orange version

##### Actual behavior

Receive  error

##### Additional info (worksheets, data, screenshots, ...)

![Step1](https://user-images.githubusercontent.com/49479001/70851944-72401d00-1e76-11ea-910d-d1110a7dcc4a.jpg)

![step2](https://user-images.githubusercontent.com/49479001/70851947-7704d100-1e76-11ea-971d-c16a58c6b424.jpg)

![step3](https://user-images.githubusercontent.com/49479001/70851950-79672b00-1e76-11ea-815f-7fa2c726285f.jpg)

![step4](https://user-images.githubusercontent.com/49479001/70851953-808e3900-1e76-11ea-85da-e12d47f0bc32.jpg)

[Errormessage.txt](https://github.com/biolab/orange3-text/files/3964081/Errormessage.txt)

**Comment by EsotericRebel** [comment]
Collecting Orange3-Text
  Downloading https://files.pythonhosted.org/packages/41/6b/1e218ef888d55748512087291c46c5719f382ce9b098f3bd78fd249c2125/Orange3_Text-0.7.5-py3-none-any.whl (17.5MB)
Requirement already satisfied: python-dateutil<2.8.1 in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from Orange3-Text) (2.8.0)
Requirement already satisfied: docutils<0.16 in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from Orange3-Text) (0.15.2)
Requirement already satisfied: scikit-learn in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from Orange3-Text) (0.21.3)
Requirement already satisfied: wikipedia in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from Orange3-Text) (1.4.0)
Collecting ufal.udpipe-temp>=1.2.0.5 (from Orange3-Text)
  Downloading https://files.pythonhosted.org/packages/20/16/dbc0e8fb9332dc6837e5c4f6d8ae3fb7355d74669cea859a0f050212c32e/ufal.udpipe-temp-1.2.0.5.tar.gz (307kB)
Requirement already satisfied: odfpy>=1.3.5 in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from Orange3-Text) (1.4.0)
Requirement already satisfied: lxml in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from Orange3-Text) (4.3.4)
Requirement already satisfied: nltk>=3.0.5 in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from Orange3-Text) (3.4.4)
Requirement already satisfied: biopython in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from Orange3-Text) (1.74)
Requirement already satisfied: scipy in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from Orange3-Text) (1.3.1)
Requirement already satisfied: simhash in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from Orange3-Text) (1.9.0)
Requirement already satisfied: setuptools-git in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from Orange3-Text) (1.2)
Requirement already satisfied: beautifulsoup4 in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from Orange3-Text) (4.7.1)
Requirement already satisfied: tweepy in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from Orange3-Text) (3.7.0)
Requirement already satisfied: Orange3<4.0a,>=3.20 in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from -c C:\Users\GEOFFR~1\AppData\Local\Temp\tmptc8vva46.txt (line 1)) (3.23.1)
Requirement already satisfied: docx2txt>=0.6 in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from Orange3-Text) (0.8)
Requirement already satisfied: pdfminer3k>=1.3.1 in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from Orange3-Text) (1.3.1)
Requirement already satisfied: gensim>=0.12.3 in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from Orange3-Text) (3.8.0)
Requirement already satisfied: numpy in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from Orange3-Text) (1.16.5)
Requirement already satisfied: six>=1.5 in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from python-dateutil<2.8.1->Orange3-Text) (1.12.0)
Requirement already satisfied: joblib>=0.11 in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from scikit-learn->Orange3-Text) (0.14.0)
Requirement already satisfied: requests<3.0.0,>=2.0.0 in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from wikipedia->Orange3-Text) (2.22.0)
Requirement already satisfied: defusedxml in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from odfpy>=1.3.5->Orange3-Text) (0.6.0)
Requirement already satisfied: soupsieve>=1.2 in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from beautifulsoup4->Orange3-Text) (1.9.2)
Requirement already satisfied: PySocks>=1.5.7 in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from tweepy->Orange3-Text) (1.7.1)
Requirement already satisfied: requests-oauthlib>=0.7.0 in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from tweepy->Orange3-Text) (1.2.0)
Requirement already satisfied: xlsxwriter in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from Orange3<4.0a,>=3.20->-c C:\Users\GEOFFR~1\AppData\Local\Temp\tmptc8vva46.txt (line 1)) (1.2.1)
Requirement already satisfied: python-louvain>=0.13 in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from Orange3<4.0a,>=3.20->-c C:\Users\GEOFFR~1\AppData\Local\Temp\tmptc8vva46.txt (line 1)) (0.13)
Requirement already satisfied: chardet>=3.0.2 in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from Orange3<4.0a,>=3.20->-c C:\Users\GEOFFR~1\AppData\Local\Temp\tmptc8vva46.txt (line 1)) (3.0.4)
Requirement already satisfied: orange-widget-base<4.1a,>=4.0a in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from Orange3<4.0a,>=3.20->-c C:\Users\GEOFFR~1\AppData\Local\Temp\tmptc8vva46.txt (line 1)) (4.0.1)
Requirement already satisfied: setuptools>=36.3 in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from Orange3<4.0a,>=3.20->-c C:\Users\GEOFFR~1\AppData\Local\Temp\tmptc8vva46.txt (line 1)) (41.4.0)
Requirement already satisfied: serverfiles in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from Orange3<4.0a,>=3.20->-c C:\Users\GEOFFR~1\AppData\Local\Temp\tmptc8vva46.txt (line 1)) (0.3.0)
Requirement already satisfied: AnyQt>=0.0.8 in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from Orange3<4.0a,>=3.20->-c C:\Users\GEOFFR~1\AppData\Local\Temp\tmptc8vva46.txt (line 1)) (0.0.10)
Requirement already satisfied: bottleneck>=1.0.0 in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from Orange3<4.0a,>=3.20->-c C:\Users\GEOFFR~1\AppData\Local\Temp\tmptc8vva46.txt (line 1)) (1.2.1)
Requirement already satisfied: matplotlib>=2.0.0 in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from Orange3<4.0a,>=3.20->-c C:\Users\GEOFFR~1\AppData\Local\Temp\tmptc8vva46.txt (line 1)) (3.1.1)
Requirement already satisfied: xlrd>=0.9.2 in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from Orange3<4.0a,>=3.20->-c C:\Users\GEOFFR~1\AppData\Local\Temp\tmptc8vva46.txt (line 1)) (1.2.0)
Requirement already satisfied: pip>=9.0 in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from Orange3<4.0a,>=3.20->-c C:\Users\GEOFFR~1\AppData\Local\Temp\tmptc8vva46.txt (line 1)) (19.2.3)
Requirement already satisfied: openTSNE>=0.3.11 in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from Orange3<4.0a,>=3.20->-c C:\Users\GEOFFR~1\AppData\Local\Temp\tmptc8vva46.txt (line 1)) (0.3.11)
Requirement already satisfied: orange-canvas-core<0.2a,>=0.1.7 in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from Orange3<4.0a,>=3.20->-c C:\Users\GEOFFR~1\AppData\Local\Temp\tmptc8vva46.txt (line 1)) (0.1.7)
Requirement already satisfied: keyrings.alt in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from Orange3<4.0a,>=3.20->-c C:\Users\GEOFFR~1\AppData\Local\Temp\tmptc8vva46.txt (line 1)) (3.1)
Requirement already satisfied: networkx in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from Orange3<4.0a,>=3.20->-c C:\Users\GEOFFR~1\AppData\Local\Temp\tmptc8vva46.txt (line 1)) (2.3)
Requirement already satisfied: pandas in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from Orange3<4.0a,>=3.20->-c C:\Users\GEOFFR~1\AppData\Local\Temp\tmptc8vva46.txt (line 1)) (0.25.1)
Requirement already satisfied: pyyaml in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from Orange3<4.0a,>=3.20->-c C:\Users\GEOFFR~1\AppData\Local\Temp\tmptc8vva46.txt (line 1)) (5.1.2)
Requirement already satisfied: keyring in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from Orange3<4.0a,>=3.20->-c C:\Users\GEOFFR~1\AppData\Local\Temp\tmptc8vva46.txt (line 1)) (19.2.0)
Requirement already satisfied: pyqtgraph>=0.10.0 in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from Orange3<4.0a,>=3.20->-c C:\Users\GEOFFR~1\AppData\Local\Temp\tmptc8vva46.txt (line 1)) (0.10.0)
Requirement already satisfied: pytest>=2.0 in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from pdfminer3k>=1.3.1->Orange3-Text) (5.2.1)
Requirement already satisfied: ply>=3.4 in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from pdfminer3k>=1.3.1->Orange3-Text) (3.11)
Requirement already satisfied: smart-open>=1.7.0 in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from gensim>=0.12.3->Orange3-Text) (1.8.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from requests<3.0.0,>=2.0.0->wikipedia->Orange3-Text) (1.25.6)
Requirement already satisfied: idna<2.9,>=2.5 in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from requests<3.0.0,>=2.0.0->wikipedia->Orange3-Text) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from requests<3.0.0,>=2.0.0->wikipedia->Orange3-Text) (2019.6.16)
Requirement already satisfied: oauthlib>=3.0.0 in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from requests-oauthlib>=0.7.0->tweepy->Orange3-Text) (3.0.2)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from matplotlib>=2.0.0->Orange3<4.0a,>=3.20->-c C:\Users\GEOFFR~1\AppData\Local\Temp\tmptc8vva46.txt (line 1)) (2.4.2)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from matplotlib>=2.0.0->Orange3<4.0a,>=3.20->-c C:\Users\GEOFFR~1\AppData\Local\Temp\tmptc8vva46.txt (line 1)) (1.1.0)
Requirement already satisfied: cycler>=0.10 in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from matplotlib>=2.0.0->Orange3<4.0a,>=3.20->-c C:\Users\GEOFFR~1\AppData\Local\Temp\tmptc8vva46.txt (line 1)) (0.10.0)
Requirement already satisfied: pynndescent>=0.3 in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from openTSNE>=0.3.11->Orange3<4.0a,>=3.20->-c C:\Users\GEOFFR~1\AppData\Local\Temp\tmptc8vva46.txt (line 1)) (0.3.3)
Requirement already satisfied: commonmark in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from orange-canvas-core<0.2a,>=0.1.7->Orange3<4.0a,>=3.20->-c C:\Users\GEOFFR~1\AppData\Local\Temp\tmptc8vva46.txt (line 1)) (0.9.1)
Requirement already satisfied: cachecontrol[filecache] in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from orange-canvas-core<0.2a,>=0.1.7->Orange3<4.0a,>=3.20->-c C:\Users\GEOFFR~1\AppData\Local\Temp\tmptc8vva46.txt (line 1)) (0.12.5)
Requirement already satisfied: decorator>=4.3.0 in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from networkx->Orange3<4.0a,>=3.20->-c C:\Users\GEOFFR~1\AppData\Local\Temp\tmptc8vva46.txt (line 1)) (4.4.0)
Requirement already satisfied: pytz>=2017.2 in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from pandas->Orange3<4.0a,>=3.20->-c C:\Users\GEOFFR~1\AppData\Local\Temp\tmptc8vva46.txt (line 1)) (2019.3)
Requirement already satisfied: entrypoints in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from keyring->Orange3<4.0a,>=3.20->-c C:\Users\GEOFFR~1\AppData\Local\Temp\tmptc8vva46.txt (line 1)) (0.3)
Requirement already satisfied: pywin32-ctypes!=0.1.0,!=0.1.1; sys_platform == "win32" in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from keyring->Orange3<4.0a,>=3.20->-c C:\Users\GEOFFR~1\AppData\Local\Temp\tmptc8vva46.txt (line 1)) (0.2.0)
Requirement already satisfied: py>=1.5.0 in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from pytest>=2.0->pdfminer3k>=1.3.1->Orange3-Text) (1.8.0)
Requirement already satisfied: packaging in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from pytest>=2.0->pdfminer3k>=1.3.1->Orange3-Text) (19.2)
Requirement already satisfied: attrs>=17.4.0 in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from pytest>=2.0->pdfminer3k>=1.3.1->Orange3-Text) (19.2.0)
Requirement already satisfied: more-itertools>=4.0.0 in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from pytest>=2.0->pdfminer3k>=1.3.1->Orange3-Text) (7.2.0)
Requirement already satisfied: atomicwrites>=1.0 in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from pytest>=2.0->pdfminer3k>=1.3.1->Orange3-Text) (1.3.0)
Requirement already satisfied: pluggy<1.0,>=0.12 in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from pytest>=2.0->pdfminer3k>=1.3.1->Orange3-Text) (0.13.0)
Requirement already satisfied: wcwidth in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from pytest>=2.0->pdfminer3k>=1.3.1->Orange3-Text) (0.1.7)
Requirement already satisfied: importlib-metadata>=0.12 in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from pytest>=2.0->pdfminer3k>=1.3.1->Orange3-Text) (0.23)
Requirement already satisfied: colorama in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from pytest>=2.0->pdfminer3k>=1.3.1->Orange3-Text) (0.4.1)
Requirement already satisfied: boto>=2.32 in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from smart-open>=1.7.0->gensim>=0.12.3->Orange3-Text) (2.49.0)
Requirement already satisfied: boto3 in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from smart-open>=1.7.0->gensim>=0.12.3->Orange3-Text) (1.9.189)
Requirement already satisfied: numba>=0.39 in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from pynndescent>=0.3->openTSNE>=0.3.11->Orange3<4.0a,>=3.20->-c C:\Users\GEOFFR~1\AppData\Local\Temp\tmptc8vva46.txt (line 1)) (0.45.1)
Requirement already satisfied: msgpack in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from cachecontrol[filecache]->orange-canvas-core<0.2a,>=0.1.7->Orange3<4.0a,>=3.20->-c C:\Users\GEOFFR~1\AppData\Local\Temp\tmptc8vva46.txt (line 1)) (0.6.2)
Requirement already satisfied: lockfile>=0.9 in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from cachecontrol[filecache]->orange-canvas-core<0.2a,>=0.1.7->Orange3<4.0a,>=3.20->-c C:\Users\GEOFFR~1\AppData\Local\Temp\tmptc8vva46.txt (line 1)) (0.12.2)
Requirement already satisfied: zipp>=0.5 in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from importlib-metadata>=0.12->pytest>=2.0->pdfminer3k>=1.3.1->Orange3-Text) (0.6.0)
Requirement already satisfied: botocore<1.13.0,>=1.12.189 in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from boto3->smart-open>=1.7.0->gensim>=0.12.3->Orange3-Text) (1.12.248)
Requirement already satisfied: s3transfer<0.3.0,>=0.2.0 in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from boto3->smart-open>=1.7.0->gensim>=0.12.3->Orange3-Text) (0.2.1)
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from boto3->smart-open>=1.7.0->gensim>=0.12.3->Orange3-Text) (0.9.4)
Requirement already satisfied: llvmlite>=0.29.0dev0 in c:\users\geoffreynl\anaconda3\envs\tensor\lib\site-packages (from numba>=0.39->pynndescent>=0.3->openTSNE>=0.3.11->Orange3<4.0a,>=3.20->-c C:\Users\GEOFFR~1\AppData\Local\Temp\tmptc8vva46.txt (line 1)) (0.29.0)
Building wheels for collected packages: ufal.udpipe-temp
  Building wheel for ufal.udpipe-temp (setup.py): started
  Building wheel for ufal.udpipe-temp (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\GeoffreyNL\Anaconda3\envs\Tensor\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\GEOFFR~1\\AppData\\Local\\Temp\\pip-install-y8w659nb\\ufal.udpipe-temp\\setup.py'"'"'; __file__='"'"'C:\\Users\\GEOFFR~1\\AppData\\Local\\Temp\\pip-install-y8w659nb\\ufal.udpipe-temp\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\GEOFFR~1\AppData\Local\Temp\pip-wheel-gy391qdw' --python-tag cp37
       cwd: C:\Users\GEOFFR~1\AppData\Local\Temp\pip-install-y8w659nb\ufal.udpipe-temp\
  Complete output (18 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  creating build\lib.win-amd64-3.7\ufal
  copying ufal\__init__.py -> build\lib.win-amd64-3.7\ufal
  copying ufal\udpipe.py -> build\lib.win-amd64-3.7\ufal
  running egg_info
  writing ufal.udpipe_temp.egg-info\PKG-INFO
  writing dependency_links to ufal.udpipe_temp.egg-info\dependency_links.txt
  writing top-level names to ufal.udpipe_temp.egg-info\top_level.txt
  reading manifest file 'ufal.udpipe_temp.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'ufal.udpipe_temp.egg-info\SOURCES.txt'
  running build_ext
  building 'ufal._udpipe' extension
  error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
  ----------------------------------------
  ERROR: Failed building wheel for ufal.udpipe-temp
  Running setup.py clean for ufal.udpipe-temp
Failed to build ufal.udpipe-temp
Installing collected packages: ufal.udpipe-temp, Orange3-Text
  Running setup.py install for ufal.udpipe-temp: started
    Running setup.py install for ufal.udpipe-temp: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\GeoffreyNL\Anaconda3\envs\Tensor\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\GEOFFR~1\\AppData\\Local\\Temp\\pip-install-y8w659nb\\ufal.udpipe-temp\\setup.py'"'"'; __file__='"'"'C:\\Users\\GEOFFR~1\\AppData\\Local\\Temp\\pip-install-y8w659nb\\ufal.udpipe-temp\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\GEOFFR~1\AppData\Local\Temp\pip-record-g0agpadk\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\GEOFFR~1\AppData\Local\Temp\pip-install-y8w659nb\ufal.udpipe-temp\
    Complete output (18 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    creating build\lib.win-amd64-3.7\ufal
    copying ufal\__init__.py -> build\lib.win-amd64-3.7\ufal
    copying ufal\udpipe.py -> build\lib.win-amd64-3.7\ufal
    running egg_info
    writing ufal.udpipe_temp.egg-info\PKG-INFO
    writing dependency_links to ufal.udpipe_temp.egg-info\dependency_links.txt
    writing top-level names to ufal.udpipe_temp.egg-info\top_level.txt
    reading manifest file 'ufal.udpipe_temp.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'ufal.udpipe_temp.egg-info\SOURCES.txt'
    running build_ext
    building 'ufal._udpipe' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\GeoffreyNL\Anaconda3\envs\Tensor\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\GEOFFR~1\\AppData\\Local\\Temp\\pip-install-y8w659nb\\ufal.udpipe-temp\\setup.py'"'"'; __file__='"'"'C:\\Users\\GEOFFR~1\\AppData\\Local\\Temp\\pip-install-y8w659nb\\ufal.udpipe-temp\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\GEOFFR~1\AppData\Local\Temp\pip-record-g0agpadk\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.

**Comment by ajdapretnar** [comment]
How did you install Orange?

**Comment by EsotericRebel** [comment]
It is an Andaconda install

**Comment by ajdapretnar** [comment]
If you are using Anaconda, you should follow instructions from our website: https://orange.biolab.si/download/#windows (see Anaconda section). This also means you are not using the latest version of Orange, because you have most likely not set the correct channel. Hence the add-on cannot be installed properly.

**Comment by ajdapretnar** [comment]
Closed due to inactivity.
