### ISSUE TITLE
Word cloud: remove words with weight 0 when showing bag of word weghts

### ISSUE THREAD

**Issue by PrimozGodec** [biolab/orange3-text#500]
#### Expected behavior

Word cloud showing only values that appear in the text.

##### Actual behavior

When I let say in Data Table select few rows also words that are not in the selected text appears in the Word Cloud widget - with weight 0. Word cloud is showing values that have weight 0. 

##### Steps to reproduce the behavior

Corpus -> bow -> data table (selection) -> word colud

**Comment by ajdapretnar** [comment]
Closed via #501.
