### ISSUE TITLE
Word Enrichment: sort by p-value

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-text#516]
##### Text version

0.8.0

##### Orange version

3.26.0.dev

##### Expected behavior
Word Enrichment sorts by p-value by default.

##### Actual behavior
It sorts by words (alphabetically).

**Comment by djukicn** [comment]
@ajdapretnar The widget is currently configured to sort by FDR in ascending order. I couldn't reproduce the case where it sorts alphabetically by default.

**Comment by ajdapretnar** [comment]
🤔 It probably should sort by p-values rather than FDR? The issue I have with FDR is that it is so often 1 for small data sets.

**Comment by djukicn** [comment]
In that case it really should sort by p-value.
