### ISSUE TITLE
Can't instal orange3-text

### ISSUE THREAD

**Issue by ferri1374** [biolab/orange3-text#517]
##### Text version

I can't install orange3-text add-on, when I select it for install, it shows me : an error occurred while running subprocess
I'm using window 10. How can I solve it?

##### Orange version
Orange3-3.25.0

**Comment by ajdapretnar** [comment]
Please provide additional information. Add-on dialogue should provide a log of the error or an option to select Show more with additional information. Please copy-paste the input here.

**Comment by ajdapretnar** [comment]
Closed due to inactivity.
