### ISSUE TITLE
Topic Modelling: Coherence?

### ISSUE THREAD

**Issue by jkaupanger** [biolab/orange3-text#539]
In performing topic modelling, the metric that I've come across for establishing how good a model is is coherence, but I can seem to figure out where that is in the widget, or if there's another widget that would display the topics' coherences. Am I missing it? Or is there a way to show/derive topic coherence?

**Comment by ajdapretnar** [comment]
For questions about Orange, please see our [Discord channel](https://discord.gg/FWrfeXV).

**Comment by ajdapretnar** [comment]
Also, no there is no coherence measure in Orange.
