### ISSUE TITLE
Error in widget Corpus

### ISSUE THREAD

**Issue by mchikurov** [biolab/orange3-text#549]
**Describe the bug**
Unable to use Corpus widget. Getting error discribed below.

**To Reproduce**
1. Go to 'Text Mining'
2. Click on 'Corpus'
3. Get error

**Orange version:**
3.23.1

**Screenshots**
![image](https://user-images.githubusercontent.com/15872944/86486892-3ebad680-bd65-11ea-9470-2db0b80fc22b.png)

**Operating system:**
Windows 10

**Comment by ajdapretnar** [comment]
Please update Orange and see if the issue persists.

**Comment by mchikurov** [comment]
Update to 3.26 helped.
