### ISSUE TITLE
Character format problem

### ISSUE THREAD

**Issue by 17865653325** [biolab/orange3-text#570]
Character format problem.

File：   orange3-text/orangecontrib/text/widgets/tests/data/good/sample_txt_ž.txt

There is a problem with the format of this document. When PIP install, an error will be reported because of the format problem. Can you take a look at this error and modify it?

**Comment by djukicn** [comment]
Hello,
I'm not able to reproduce the behavior you're explaining. Can you provide us with the steps you took before getting the error and the text of the error message?

**Comment by ajdapretnar** [comment]
Closed due to inactivity.

**Comment by 17865653325** [comment]
> Hello,
> I'm not able to reproduce the behavior you're explaining. Can you provide us with the steps you took before getting the error and the text of the error message?
![image](https://user-images.githubusercontent.com/68682057/100422073-8cddc700-30c4-11eb-89e9-401503740e9f.png)
 When PIP install, This garbled code will report an error
![image](https://user-images.githubusercontent.com/68682057/100426554-05945180-30cc-11eb-8d63-7afee7ee28c2.png)

After deleting the file sample_txt_ž.txt, it runs successfully
![image](https://user-images.githubusercontent.com/68682057/100426895-8ce1c500-30cc-11eb-8751-80c7dcd54b7b.png)

**Comment by ajdapretnar** [comment]
This is not garbled code. It is a legitimate file with a legitimate file name under utf-8. The error you are showing has nothing to do with the file, it says you are missing pybind11. Perhaps it is a pybind11 issue.
