### ISSUE TITLE
Text Mining widgets broken in fresh install

### ISSUE THREAD

**Issue by NetwarSystem** [biolab/orange3-text#578]
Both the Corpus Viewer and Word Cloud generate this error for me as soon as I put them on the canvas. I reinstalled Anaconda Orange3 version 3.26.0 fresh, and Orange3-Text 1.1.0, still have the same issue.

_AttributeError: module 'Orange.widgets.gui' has no attribute 'WebviewWidget'_

Ubuntu Budgie 20.04

A fresh install of Anaconda using this:
NAME:  Anaconda3
VER:   2020.07
PLAT:  linux-64
LINES: 586
MD5:   8a581514493c9e0a1cbd425bc1c7dd90

Conda reports
orange-canvas-core        0.1.15                     py_0    conda-forge
orange-widget-base        4.8.0                      py_0    conda-forge
orange3                   3.26.0           py38h950e882_0    conda-forge
orange3-text              0.7.3                      py_0    conda-forge

Full package list:

https://gist.github.com/NetwarSystem/afe9c97dccc9b16265797c146beb2494

Full error report:

https://gist.github.com/NetwarSystem/8cfab8961fa60786ec7dcbd0d5137dd9

Am new to Orange but I do some Python development. If there is more I need to do to help isolate this, just point me towards the procedure.

**Comment by ajdapretnar** [comment]
Your text add-on seems to be old. 🤔 This is strange, because you seem to have the conda-forge channel on and there's v 1.1.0 available (https://github.com/conda-forge/orange3-text-feedstock).

Could you go to Options - Add-ons and update Text add-on? It should offer version 1.1.0. Alternatively, you can use `pip install -U orange3-text`.

Let me know how it goes.

**Comment by NetwarSystem** [comment]
Looks like it was my goofy desktop environment. I had installed Anaconda some time ago, couldn't get Rapids.ai to install properly, so I manually removed it from service. Looks like the old version of Text was a legacy from that time. It's strange that a reinstall didn't clear that up.

I just rm -rf ~/Anaconda3

I presume this is going to resolve the issue.

**Comment by NetwarSystem** [comment]
Just watched conda install orange3-text-0.7.3 

https://gist.github.com/NetwarSystem/a772d3c0f36db43c1dcd525f48f27f01

and it won't do orange3-text-1.1.0

I have more than one computer, will try install from scratch on one of them.

**Comment by ajdapretnar** [comment]
Have you tried updating from the dialogue?

**Comment by ajdapretnar** [comment]
Closed due to inactivity.
