### ISSUE TITLE
"Selected Topic" of  Topic modelling should show corpus of that topic

### ISSUE THREAD

**Issue by zy-tech** [biolab/orange3-text#587]
I would like to see the corpus of the selected topic in "topic modelling" wedget, but what I got is the topic words.

Could we get the corpus belongs to the topic(s) I seleted?

**Comment by ajdapretnar** [comment]
That's not how topic modelling works. There is no corpus that belongs to one topic. Each document has a probability for each topic, so what you'd end up with in the end, is the entire corpus. Look at the Corpus output to see what I mean. I believe this is a wontfix.
