### ISSUE TITLE
Product classification

### ISSUE THREAD

**Issue by Jeo87** [biolab/orange3-text#593]
**I want to classify suppliers using suppler name and product description in the purchase order (PO Description); for that, I did the following steps
1.	Imported the data in CSV format manually identifying the columns as bellow
a.	Supplier name = S, Meta
b.	PO Description = S
c.	Category = D, class
2.	Connected corpus
3.	Cleansed the data using preprocess text
4.	Connected bag of words
5.	Connected Learner ( Logistic Regression)
The process fails at the learner Stage; the error message is “Fitting Failed. Unable to allocate zero bytes for an array with shape (538686,0) and datatype float 64)”
I intend to predict the categories for the unseen data using this training set.
Please Help
Thanks
**
I am not able to attach the file hence please find the link to my onedrive

Workflow : https://bigbigchina-my.sharepoint.com/:u:/g/personal/v6224_vip365_tech/EUN5UsskYlNCmj_H9-Bg8q0Brs-jKjtbQLrzrPk1dVpSuQ?e=FocNvl

Dataset : https://bigbigchina-my.sharepoint.com/:x:/g/personal/v6224_vip365_tech/EY0S2piO5qZJh0RnSO-unkIB524huYVGLaKZtuRdOWEIKg?e=qkfOli

**Comment by ajdapretnar** [comment]
@Jeo87 We would need more details. I suggest sending a zip file of the workflow and the data, if the data is not private (it can be a sample of the data, as long as it produces the same error)

**Comment by Jeo87** [comment]
hi @ajdapretnar thanks for the quick reply I am trying to to zip and attach the workflow but it is giving me an error as it is more than 10mb, is there an alternate way to attach the file?

**Comment by ajdapretnar** [comment]
Downsample the data. Just use the first 100 rows or something.

**Comment by Jeo87** [comment]
Hi @ajdapretnar I have shared my onedrive link in the original query, is that ok?

**Comment by ajdapretnar** [comment]
I've been trying to get your workflow running the entire weekend. I can't. It's simply too big and I'm running out of memory. Please reproduce the issue with a smaller data set. Also, please clear the settings with Options - Reset widget settings. This will remove all previously saved files and make the workflow much much smaller.

**Comment by ajdapretnar** [comment]
Closed due to inactivity.
