### ISSUE TITLE
ERROR:orangewidget.workflow.widgetsscheme:'Network' is not valid signal name for 'Corpus to Network'

### ISSUE THREAD

**Issue by patrickdrouin** [biolab/orange3-text#600]
Hello,

I can't seem to be able to obtain a network out of Corpus to Network. In fact, I believe it does generate one but it does not seem to be available for the next widgets (in my case Network Explorer). 

Corpus to network says: Undirected network with 567 nodes and 31 edges.

However, the link from Corpus to Network to Network Explorer does not contain a Network option. 

Patrick

**Comment by ajdapretnar** [comment]
I do not quite understand. 640-twitter.ows does not have Corpus to Network. Did you connect it manually? I am not sure how this resulted in the above error, as it normally occurs only when an old workflow is loaded in a new environment (and we forgot to migrate some settings).

Would you mind adding a screenshot or perhaps a whole workflow that reproduces the error?

**Comment by patrickdrouin** [comment]
@ajdapretnar Sorry for the confusion. I started with the demo and modified it. Here are the screenshots.  It might just be a misunderstanding on my part. 

> 
![Screenshot from 2020-11-23 11 07 03](https://user-images.githubusercontent.com/2301477/99985794-66debc80-2d7c-11eb-8bb0-01a6d16a113b.jpeg)
![Screenshot from 2020-11-23 11 06 46](https://user-images.githubusercontent.com/2301477/99985797-67775300-2d7c-11eb-80bc-2c2d71d14022.jpeg)
![Screenshot from 2020-11-23 11 01 34](https://user-images.githubusercontent.com/2301477/99985799-680fe980-2d7c-11eb-8946-f4d1cde80121.jpeg)
![Screenshot from 2020-11-23 11 00 51](https://user-images.githubusercontent.com/2301477/99985800-680fe980-2d7c-11eb-89e3-ce99ed5a21e5.jpeg)

**Comment by ajdapretnar** [comment]
@patrickdrouin Could you please go to View - Log and paste the output of Log here?

**Comment by ajdapretnar** [comment]
I can confirm this happens because Network add-on is installed after Text, so Text registers no Network and once Network is installed, forgets to add the output.

Fixed and will be available in the next release.

**Comment by patrickdrouin** [comment]
@ajdapretnar Works like a charm! Thanks!
