### ISSUE TITLE
Sentiment analysis not work

### ISSUE THREAD

**Issue by Dragnellm** [biolab/orange3-text#606]
**Describe the bug**

Sentiment Analysis not work, the function crash 
**To Reproduce**

**Expected behavior**

This is the error self._supported_languages = [re.search(regex, i[0]).group(0) for i in
AttributeError: 'NoneType' object has no attribute 'group' This is the error
**Orange version:**
Orange - About - version number.
3.26 - 3.27

**Text add-on version:**
Options - Add-ons - version number.
1,20

**Screenshots**
![image](https://user-images.githubusercontent.com/28069241/101833989-bb699200-3b07-11eb-8e03-da9a78e9e0d5.png)

![image](https://user-images.githubusercontent.com/28069241/101834009-c1f80980-3b07-11eb-944f-2582068069b0.png)

**Operating system:**
Windows, OSX or Linux? Which version?

OSX Big Surf
**Additional context**

**Comment by jcg44** [comment]
I had the same issue.  Running Orange 3.27.1 on Windows 10.0.19041.  Sentiment analysis worked yesterday (Dec 9, 2020) but won't load today even for Orange workspaces that already had that widget.  I tried uninstalling Text and reinstalling it, and it didn't help.  Thanks!

**Comment by Dragnellm** [comment]
I tried install in Windows and Linux, but not worked sentiment analysis. And I need to perform an analysis in multilingual sentiment :(, Help :c

**Comment by ajdapretnar** [comment]
I might have botched this yesterday. 🙈 Will check it.

**Comment by ajdapretnar** [comment]
It should work now. I have added new files, which broke the loading of old files. Sorry about that. Will fix the code so that it doesn't break in the future.

**Comment by Dragnellm** [comment]
Thank's, it's work now.  🐵
