### ISSUE TITLE
Extracting data from a specific Twitter hashtag by using Orange

### ISSUE THREAD

**Issue by Shaimaai** [biolab/orange3-text#611]
Hi everyone, when I extract data from specific hashtag by using Orange3, I only get 40 tweets as max. Anyone can help? Thanks

**Comment by ajdapretnar** [comment]
This is normal. Twitter API allows access to data from the past 14 days. It could be there are only 40 tweets matching this condition. This is a limitation of Twitter API, not of Orange.
