### ISSUE TITLE
Error encountered in widget Import Documents in Text Mining Add-on

### ISSUE THREAD

**Issue by Ssaurabhsingh** [biolab/orange3-text#612]
**Describe the bug**
While importing a .txt file 'Text Mining Add-on' using the widget Import Documents, I encountered an error. 
Error: "Traceback (most recent call last):
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/orangecontrib/text/widgets/owimportdocuments.py", line 563, in cancel
    assert self.__pendingTask is not None
AssertionError"

**To Reproduce**
1. Go to 'Text Mining'
2. Click on 'Import Document'
3. Select a file to .txt file to import

**Expected behavior**
I expected the file to be imported error-free. But I am unable to upload any file to this now.

**Orange version:**
Orange3 - 3.27.1

**Text add-on version:**
Options - Add-ons - 1.2.0

**Screenshots**
![image](https://user-images.githubusercontent.com/76957254/103550557-fc538d00-4ea0-11eb-93cb-ee258c6b5a7b.png)

**Operating system:**
macOS Catalina 10.15.6

**Comment by ajdapretnar** [comment]
@PrimozGodec Would you perhaps know anything about this? Seems like a threading error?

**Comment by PrimozGodec** [comment]
That is threading error. I will take a look.

**Comment by PrimozGodec** [comment]
While discovering the widget's code I do not see what could be a reason :( I also cannot reproduce the error. :( @ajdapretnar have you tried to reproduce this error?

@Ssaurabhsingh what happens if you `reset widgets settings` in `Options` dialog? Does after resetting the issue still persist?

**Comment by ajdapretnar** [comment]
No, I wasn't able to reproduce this either. Perhaps, @Ssaurabhsingh you can provide a subset of the data which crashes the widget and the workflow.

**Comment by Ssaurabhsingh** [comment]
Hey @PrimozGodec , I used the reset widgets settings in Options dialog but I face the same error. 
@ajdapretnar - the 'Import Document' takes the whole folder to import rather than just a file. the folder I am trying to upload has a .txt file in it. 

I remember this error popped first when I canceled a folder upload before-hand. Post that, every time I upload any new folder with my files, I get the same error.

**Comment by ajdapretnar** [comment]
> the 'Import Document' takes the whole folder to import rather than just a file

Yes, I know. I was asking for a subset of documents so that we can reproduce the issue. I have tried loading and cancelling import several times, but I get no such error.

**Comment by Tayme-a** [comment]
I am having the same error, I cannot upload any file

**Comment by Tayme-a** [comment]
@Ssaurabhsingh Were you able to resolve the error

**Comment by ajdapretnar** [comment]
Closed due to inactivity. Reopen with a dataset to reproduce.
