### ISSUE TITLE
Custome dictionary not available for sentiment analysis panel

### ISSUE THREAD

**Issue by DaiZack** [biolab/orange3-text#614]
- Operating system: win10
- Orange version: 3.27.1
- How you installed Orange: standalone
Custome dictionary is not available for the sentiment analysis panel. it shows in the document but not in my panel

![image](https://user-images.githubusercontent.com/45176371/105110908-b3e5c300-5a8d-11eb-819a-fb3030a7d2cb.png)

**Comment by ajdapretnar** [comment]
Yes, the add-on has not been released yet.

**Comment by ajdapretnar** [comment]
Fixed via https://github.com/biolab/orange3-text/commit/08e65f29819e79a481c32203b07f18d82110e012.
