### ISSUE TITLE
AttributeError: module 'Orange.widgets.gui' has no attribute 'WebviewWidget'

### ISSUE THREAD

**Issue by madegomez** [biolab/orange3-text#621]
I am trying to use the example workflow of text mining. And I have that error when I use corpus viewer or word cloud.
I'm using Text Preprocessing workflow.
![Captura de pantalla de 2021-01-29 18-52-43](https://user-images.githubusercontent.com/59454704/106339302-2d3a9e00-6264-11eb-8e4f-47b800ea330b.png)

Orange - 3.27.0
Operation systema: Ubuntu 20.04
orange3-text 1.3.1
Please help.

**Comment by ajdapretnar** [comment]
Well, you need to install WebView. It is not included in the [installation instructions](https://github.com/biolab/orange3/wiki/Installation-on-Ubuntu-16.04-LTS), so feel free to add the line to Wiki.
