### ISSUE TITLE
crash on multilple features

### ISSUE THREAD

**Issue by davidemorselli** [biolab/orange3-text#623]
**Describe the bug**
orange crash as soon as wordcloud, document map or corpus view are dragged on the canvas

**Operating system:**
Linux MINT 19.3

**Comment by ajdapretnar** [comment]
Thank you for the report, but you are going to have to be more specific than that. Please post any error logs you are encountering and add details on how you installed Orange.

**Comment by davidemorselli** [comment]
thank you fro the reply,

I get a Segmentation fault (core dumped) in the terminal. where can I find a log?
I installed it via conda (and also tried via pip, with same results)

**Comment by ajdapretnar** [comment]
Would you mind running Orange with `python -m Orange.canvas -l 4`, repeating the process and submitting the log here? Also, we would appreciate a minimal (non)working example. :)

**Comment by davidemorselli** [comment]
here's the log

INFO:__main__:Starting 'Orange Canvas' application.
DEBUG:__main__:Starting CanvasApplicaiton with argv = ['/home/dmorsell/anaconda3/lib/python3.7/site-packages/Orange/canvas/__main__.py'].
INFO:qasync:Using Qt Implementation: PyQt5
DEBUG:asyncio:Using selector: _Selector
INFO:__main__:Adding search path 'orange' for prefix, 'canvas_icons'
INFO:orangecanvas.application.canvasmain:Setting up Canvas main window.
DEBUG:orangecanvas.config:Activating configuration for <Orange.canvas.config.Config object at 0x7f8f7abeedd0>
DEBUG:orangewidget.workflow.widgetsscheme:Scheme node properties sync (changed: False)
DEBUG:orangecanvas.gui.stackedwidget:Stack transition start ()
DEBUG:orangecanvas.gui.stackedwidget:Stack transition finished ()
DEBUG:orangecanvas.registry.cache:Loading widget registry cache ('/home/dmorsell/.cache/Orange/3.28.0.dev/registry-cache.pck').
INFO:__main__:Running widget discovery process.
INFO:orangecanvas.registry.discovery:Ignoring '/home/dmorsell/anaconda3/lib/python3.7/site-packages/Orange/widgets/visualize/owscatterplotgraph.py'.
INFO:orangecanvas.registry.discovery:Ignoring '/home/dmorsell/anaconda3/lib/python3.7/site-packages/Orange/widgets/visualize/owscatterplotgraph_obsolete.py'.
INFO:orangecanvas.registry.discovery:Ignoring '/home/dmorsell/anaconda3/lib/python3.7/site-packages/Orange/widgets/visualize/owtreeviewer2d.py'.
INFO:orangecanvas.registry.discovery:Ignoring '/home/dmorsell/anaconda3/lib/python3.7/site-packages/Orange/widgets/visualize/pythagorastreeviewer.py'.
INFO:orangecanvas.registry.discovery:Ignoring '/home/dmorsell/anaconda3/lib/python3.7/site-packages/Orange/widgets/evaluate/contexthandlers.py'.
INFO:orangecanvas.registry.discovery:Ignoring '/home/dmorsell/anaconda3/lib/python3.7/site-packages/Orange/widgets/evaluate/utils.py'.
DEBUG:sql_log:Logging started: 2021-02-09 10:08:07
DEBUG:orangecanvas.registry.cache:Saving widget registry cache with 142 entries ('/home/dmorsell/.cache/Orange/3.28.0.dev/registry-cache.pck').
DEBUG:orangecanvas.registry:'set_global_registry()' - setting registry.
INFO:__main__:Not sending usage statistics (disabled).
INFO:__main__:Entering main event loop.

when I drag the worldcloud widget on the canvas this happens:

INFO:orangecanvas.scheme.scheme:Added node 'Word Cloud' to scheme ''.
DEBUG:orangewidget.workflow.widgetsscheme:Scheme node properties sync (changed: False)
DEBUG:orangecanvas.document.schemeedit:Modified strict check (modified flag: False, undo stack clean: False, properties: True)
DEBUG:orangecanvas.scheme.widgetmanager:__process_init_queue: 'Word Cloud'
DEBUG:orangecanvas.scheme.widgetmanager:Creating widget for node SchemeNode(description_id='orangecontrib.text.widgets.owwordcloud', title='Word Cloud', ...)
INFO:orangewidget.workflow.widgetsscheme:WidgetManager: Creating 'orangecontrib.text.widgets.owwordcloud.OWWordCloud' instance 'Word Cloud'.
Segmentation fault (core dumped)

not sure how to transmit you an example. Orange crashes as soon as I drag the widget (with an empty canvas)

**Comment by ajdapretnar** [comment]
Ok, then indeed it might be something with a workflow. You can submit the data (if possible) and the workflow until the point of connecting the Word Cloud to it.

**Comment by davidemorselli** [comment]
with document map widget:

INFO:orangecanvas.scheme.scheme:Added node 'Document Map' to scheme ''.
DEBUG:orangewidget.workflow.widgetsscheme:Scheme node properties sync (changed: False)
DEBUG:orangecanvas.document.schemeedit:Modified strict check (modified flag: False, undo stack clean: False, properties: True)
DEBUG:orangecanvas.scheme.widgetmanager:__process_init_queue: 'Document Map'
DEBUG:orangecanvas.scheme.widgetmanager:Creating widget for node SchemeNode(description_id='orangecontrib.text.widgets.owdocmap', title='Document Map', ...)
INFO:orangewidget.workflow.widgetsscheme:WidgetManager: Creating 'orangecontrib.text.widgets.owdocmap.OWDocMap' instance 'Document Map'.
Segmentation fault (core dumped)

**Comment by davidemorselli** [comment]
and with corpus viewer:

INFO:orangecanvas.scheme.scheme:Added node 'Corpus Viewer' to scheme ''.
DEBUG:orangewidget.workflow.widgetsscheme:Scheme node properties sync (changed: False)
DEBUG:orangecanvas.document.schemeedit:Modified strict check (modified flag: False, undo stack clean: False, properties: True)
DEBUG:orangecanvas.scheme.widgetmanager:__process_init_queue: 'Corpus Viewer'
DEBUG:orangecanvas.scheme.widgetmanager:Creating widget for node SchemeNode(description_id='orangecontrib.text.widgets.owcorpusviewer', title='Corpus Viewer', ...)
INFO:orangewidget.workflow.widgetsscheme:WidgetManager: Creating 'orangecontrib.text.widgets.owcorpusviewer.OWCorpusViewer' instance 'Corpus Viewer'.
Segmentation fault (core dumped)

**Comment by davidemorselli** [comment]
> Ok, then indeed it might be something with a workflow. You can submit the data (if possible) and the workflow until the point of connecting the Word Cloud to it.

the workflow is empty. it really crashes as soon as I drag the widgets in the canvas (but I have tried also with a more elaborated workflow). The other widgets work fine

[untitled.ows.zip](https://github.com/biolab/orange3-text/files/5950187/untitled.ows.zip)

**Comment by ajdapretnar** [comment]
I believe there might be an issue with your installation. Could you help @markotoplak? I suspect WebView. How could we debug?

**Comment by davidemorselli** [comment]
thanks for the support. For info, I have also tried to install the development version, and with pip or conda. always same result. 
my current version is 3.28dev, but had the same errors with the 3.26

**Comment by fahminlb33** [comment]
I'm also experiencing the same problem when I install using pip (3.27.1). But I don't have problems when I install Orange using conda (3.26.0) from anaconda channel (not conda-forge).

![image](https://user-images.githubusercontent.com/8360880/110324768-059bda00-8049-11eb-81cd-3f0825c2c7f3.png)

Logs:

```
INFO:orangewidget.workflow.widgetsscheme:WidgetManager: Creating 'orangecontrib.text.widgets.owcorpus.OWCorpus' instance 'Corpus'.
E:\app-store\bin\miniconda3\envs\orange3\lib\site-packages\orangewidget\workflow\widgetsscheme.py:736: FutureWarning: `id` parameter is deprecated and will be removed in v0.2
  super().send(node, channel, value, signal_id)
DEBUG:orangecanvas.scheme.signalmanager:'Corpus' sending <class 'orangecontrib.text.corpus.Corpus'> (id: (1, 'Corpus', None)) on channel 'Corpus'
INFO:orangecanvas.scheme.scheme:Added node 'Corpus Viewer' to scheme ''.
DEBUG:orangewidget.workflow.widgetsscheme:Scheme node properties sync (changed: True)
DEBUG:orangecanvas.document.schemeedit:Modified strict check (modified flag: False, undo stack clean: False, properties: True)
DEBUG:orangewidget.workflow.widgetsscheme:Scheme node properties sync (changed: False)
DEBUG:orangecanvas.scheme.widgetmanager:__process_init_queue: 'Corpus Viewer'
DEBUG:orangecanvas.scheme.widgetmanager:Creating widget for node SchemeNode(description_id='orangecontrib.text.widgets.owcorpusviewer', title='Corpus Viewer', ...)
INFO:orangewidget.workflow.widgetsscheme:WidgetManager: Creating 'orangecontrib.text.widgets.owcorpusviewer.OWCorpusViewer' instance 'Corpus Viewer'.

(orange3) C:\Windows\System32>
```

**Comment by ajdapretnar** [comment]
This is expected. One cannot install Orange properly on Windows with pip. Hence we provide conda packages.

**Comment by fahminlb33** [comment]
So the solution is to install Orange through conda, but I can't get newest Orange from conda-forge, conda always uses anaconda channel even when I specify `-c conda-forge` explicitly.

**Comment by ajdapretnar** [comment]
Well then that's an issue with conda, even though I have never had this issue before.

**Comment by irgolic** [comment]
@fahminlb33 Seems the issue isn't with pip, following the discussion in biolab/orange3#5316

**Comment by ajdapretnar** [comment]
No, @fahminlb33's issue is likely with pip. @davidemorselli's issue, who posted the original question, is not with pip.

**Comment by ajdapretnar** [comment]
I will close due to inactivity. If the issue persists, please provide `pip freeze` | `conda list` outputs and reopen.
