### ISSUE TITLE
Widget UI changes following new orange-widget-base release

### ISSUE THREAD

**Issue by irgolic** [biolab/orange3-text#624]
Following the merge and release of https://github.com/biolab/orange-widget-base/pull/130, widgets will look a bit different. All widgets should be checked and adjusted.

See https://github.com/biolab/orange-widget-base/wiki/Widget-UI

**Comment by ajdapretnar** [comment]
Issues:
- Preprocess Text: too wide, redundant space to the right of control area
<img width="1146" alt="Screen Shot 2021-03-05 at 12 00 06" src="https://user-images.githubusercontent.com/12524972/110106930-91dca180-7daa-11eb-8ae8-00f59cf9b64e.png">

- Topic Modelling: too tall, a bit wide, but less problematic overall. Main "issue" for me a boxes around method parameters which seem redundant (they say "Options", which is self-evident)
<img width="878" alt="Screen Shot 2021-03-05 at 12 00 15" src="https://user-images.githubusercontent.com/12524972/110106946-9739ec00-7daa-11eb-9021-29b8e8dec63a.png">

- Statistics: a disaster, probably needs a rubber somewhere. Too tall, Apply should be centered. Also + and x icons are kind of cut (but this is an issue already on master).
<img width="318" alt="Screen Shot 2021-03-05 at 12 00 35" src="https://user-images.githubusercontent.com/12524972/110106955-9b660980-7daa-11eb-8dd4-6bc8ebdf5ece.png">

- Concordance: should be wider
<img width="600" alt="Screen Shot 2021-03-05 at 12 00 54" src="https://user-images.githubusercontent.com/12524972/110106971-a02abd80-7daa-11eb-93c9-b6bd85b4cf49.png">

- Document Map: too tall, too narrow (should be wider than taller)
<img width="365" alt="Screen Shot 2021-03-05 at 12 00 43" src="https://user-images.githubusercontent.com/12524972/110106997-a6b93500-7daa-11eb-8fb8-1357bc4aad6a.png">


A general tendency is for widgets to be taller than wider. Most, however, are same or better now.
@irgolic How to fix these issues? Custom layouts, SizeHints?

**Comment by irgolic** [comment]
> Preprocess Text: too wide, redundant space to the right of control area

<img alt="Screen Shot 2021-03-05 at 12 00 06" width="1146" src="https://user-images.githubusercontent.com/12524972/110106930-91dca180-7daa-11eb-8ae8-00f59cf9b64e.png">

Is it possible that one of the preprocessors is really elaborate and genuinely has such a wide sizeHint? If that's the case, set a sizeHint. You can put a sizeHint either on that one preprocessor's UI, the mainArea, or the widget window itself.
 
> Topic Modelling: too tall, a bit wide, but less problematic overall. Main "issue" for me a boxes around method parameters which seem redundant (they say "Options", which is self-evident)
<img alt="Screen Shot 2021-03-05 at 12 00 15" width="878" src="https://user-images.githubusercontent.com/12524972/110106946-9739ec00-7daa-11eb-9021-29b8e8dec63a.png">

That's a really weird widget. Do the options automatically show/hide as radio buttons are pressed? If that's the case, put the three radio buttons to the top, and keep an Options box below them which changes its contents.

> Statistics: a disaster, probably needs a rubber somewhere. Too tall, Apply should be centered. Also + and x icons are kind of cut (but this is an issue already on master).
<img alt="Screen Shot 2021-03-05 at 12 00 35" width="318" src="https://user-images.githubusercontent.com/12524972/110106955-9b660980-7daa-11eb-8dd4-6bc8ebdf5ece.png">

`want_main_area = False`?
Also, see Create Class. If that one's ugly too, let's talk about how we could rework these.

> Concordance: should be wider
<img alt="Screen Shot 2021-03-05 at 12 00 54" width="600" src="https://user-images.githubusercontent.com/12524972/110106971-a02abd80-7daa-11eb-93c9-b6bd85b4cf49.png">

I might fix this one in orange-widget-base. 

> Document Map: too tall, too narrow (should be wider than taller)
<img alt="Screen Shot 2021-03-05 at 12 00 43" width="365" src="https://user-images.githubusercontent.com/12524972/110106997-a6b93500-7daa-11eb-8fb8-1357bc4aad6a.png">

If this is mainArea, set a sizeHint, or refactor it to controlArea. If it IS controlArea, then is `want_main_area = True`? 

> @irgolic How to fix these issues? Custom layouts, SizeHints?

Setting a sizeHint should be foolproof if it's statically sized. If the size depends on the data, you'll want to allow its sizeHint to propagate. Also keep in mind, due to this, widgets may open at different sizes depending on if you open it with a connected data signal or not.

Right now a controlArea + mainArea widget sets its sizeHint height depending on the controlArea+buttonArea's height (with a minimum of 500), and sets a width aiming to make the mainArea square-ish, a bit wider than a square. I'll change it to also take into account the mainArea's sizeHint, so something like Concordance doesn't happen, assuming that the table in Concordance does indeed expose a larger width/height than is observed.

**Comment by ajdapretnar** [comment]
Thanks, I will have a look! I did not realize the ugly formatting was a result of legacy code, but it does make sense.

**Comment by ajdapretnar** [comment]
Statistics already sets `want_main_area = False`, so I don't know what to do with it. The others I think I can fix.

**Comment by ajdapretnar** [comment]
Looking at it, Topic Modelling has a similar behaviour to Discretize. I am not sure I would extract options from under the methods. 🤔 I am not against it, just thinking it would be in line with other such widgets.

**Comment by irgolic** [comment]
> Statistics already sets `want_main_area = False`, so I don't know what to do with it. The others I think I can fix.

The implementation should follow Create Class, right? Perhaps this is also relevant to https://github.com/biolab/orange3/issues/5285.

**Comment by ajdapretnar** [comment]
Create Class also open unnecessarily tall, but it is less noticeable as the widget has more controls.
