### ISSUE TITLE
New widget: Word list

### ISSUE THREAD

**Issue by PrimozGodec** [biolab/orange3-text#630]
**Input**: Words (Data Table)
**Outputs**: Words (Table), Selected Words (Table)

Input has to include at least one string variable, from where the widget extracts the list of words (one row each, it restricts the terms to the first three words, and provides a warning about truncation). Words from the input are automatically added to the list of words, according to the Update rule (Mute means nothing happens).

Words in the list can be edited (double click), added (with plus button at the bottom), deleted (delete button or - button at the bottom). See edit domain widget for +/- buttons.

Wordlist can be saved in the library, read from the text document (More > Import Words from File...), or saved (More > Save Words to File...). Input files can be anything that can store textual content (file with words as rows?), including an ontology (@VesnaT I can help you with ontologies). (See Python Script for similar functionality.)
When the user clicks on the update button list saves to widget settings, when the user uses the Save words to file option word list saves to File (and settings do not update).

On the output, the data Data contains a Data Table with a list of Words (current word list). The output table has one column (with name words). Selected Words output has one “Words” column, and only selected words (Selected Words). Words column is a String variable and has the attribute `{“type”: “words”}` in both outputs.

![pasted image 0](https://user-images.githubusercontent.com/6421558/110643448-672c8780-81b4-11eb-870e-8ba15d752d66.png)

**Comment by VesnaT** [comment]
Proposed UI:
![image](https://user-images.githubusercontent.com/11465003/110926750-125c4e80-8325-11eb-8c3a-48c9119aff52.png)

Feel free to comment.

**Comment by ajdapretnar** [comment]
I like it. The up and down arrows might be a bit confusing - in Edit Domain they are used for ordering individual items, while here I think they sort the entire list? Should we have "Sort" button instead (longer, uglier, but more precise)? Or is "S" for sorting? In this case, why would we need moving items up or down?

Other than this nitpicking, it looks as discussed. 👍

**Comment by VesnaT** [comment]
This should be clearer:
![image](https://user-images.githubusercontent.com/11465003/110927501-002ee000-8326-11eb-9bdf-38c557a0ce94.png)

Up/down.. if some wanted an arbitrary order, I guess, not alphabetical. I can add drag/drop functionality instead.

**Comment by lanzagar** [comment]
Notes from preliminary discussion:
- Names of library entries are currently "Untitled" by default - maybe they should have numbers to be unique (Untitled 1, ...)
- When Intersection, Union, or Only input are selected, editing/adding/removing words is disabled (to edit: copy the result into a new library entry first)
- Intersection and Union should retain word order with the Library being the primary source
- Clarify and rethink the guideline from original issue:
"it restricts the terms to the first three words, and provides a warning about truncation"
If the whole contents are not what the user wants, the first three words are almost certainly not either. If performance is an issue, we might as well truncate to a fixed length which is simpler&safer?
Maybe we could simplify to just opening ascii files and reading each row as a string (to avoid dealing with file formats and structured data).
- To discuss: reading ontology files? Maybe move this functionality to a specialized widget and use the Input signal?
- Which Update is default (Intersection, Union, ...)?
