### ISSUE TITLE
Couldn't get the text add-on installed on MacBook Orange3

### ISSUE THREAD

**Issue by Crystal-cxyz** [biolab/orange3-text#633]
I downloaded Orange 3 on my Macbook.

When I try to install the text add-on to do the text mining, the following error message keeps showing:

"Command failed: python python -m pip install text Orange3-Text==1.3.1 exited with non zero status.

ERROR: Could not find a version that satisfies the requirement text (from versions: none)
ERROR: No matching distribution found for text
WARNING: You are using pip version 19.3.1; however, version 21.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command."

I have tried to download the pi file on terminal, but it didn't work. 

I also have the python 3 install on my laptop.

**Comment by ajdapretnar** [comment]
@Crystal-cxyz Thank you for reporting this. I am going to need a bit more information.
Which OS version are you running?
I assume you installed Orange with the dmg installer? And tried to install Text add-on via the add-on dialogue (in Options - Add-ons)?
What happens, if you [download](https://github.com/biolab/orange3-text/releases/tag/1.3.1) the wheel (the file ending with .whl), then drag and drop it on to the add-on dialogue (where you are installing the add-ons), then run the installation? Does this work?

**Comment by Crystal-cxyz** [comment]
@ajdapretnar  Thank you for the comment.

 My mac is having the MacOS Catalina version 10.15.7. I did install Orange with the dmg.

I just tried with the wheel, it shows the error again:

"Command failed: python python -m pip install text /Users/crystalliu/Downloads/Orange3_Text-1.3.1-py3-none-any.whl exited with non zero status."
Also, under detail, it shows the same error and waring message from above.

I am not sure if it is something wrong with python installed. I did use the command "pip install --upgrade pip" to install the pip 21.
This time I installed it successfully with the ending line showing "Successfully installed pip-21.0.1"

After that, I still can't have the text add-on.

**Comment by ajdapretnar** [comment]
@Crystal-cxyz Pip is a package installer for Python and as such does not directly affect the installation of Text (i.e. you should be able to install even with an older version). You probably upgraded pip in your own Python environment, while Orange creates its own.
When installing in the dialogue, you should be able to see "Show details..." button. Please click it and paste the log here.

**Comment by Crystal-cxyz** [comment]
Here is the detail:

ERROR: Could not find a version that satisfies the requirement text (from versions: none)
ERROR: No matching distribution found for text
WARNING: You are using pip version 19.3.1; however, version 21.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by ajdapretnar** [comment]
This are the same details as above. I believe there should be more details when clicking on the Show Details button. Would you mind adding screenshots as well?

**Comment by Crystal-cxyz** [comment]
I don't understand about more details. That's what I have all the time. 
![Uploading Screen Shot 2021-03-23 at 16.17.01.png…]()
![Uploading Screen Shot 2021-03-23 at 16.17.09.png…]()

**Comment by Crystal-cxyz** [comment]
![Screen Shot 2021-03-23 at 16 17 01](https://user-images.githubusercontent.com/55119278/112231771-98657880-8bf4-11eb-966d-e4e16c727ece.png)
![Screen Shot 2021-03-23 at 16 17 09](https://user-images.githubusercontent.com/55119278/112231777-9a2f3c00-8bf4-11eb-96d2-a26d8e8d058d.png)

**Comment by ajdapretnar** [comment]
Ok, I am lost with this one. Any ideas @PrimozGodec?

**Comment by Crystal-cxyz** [comment]
I just removed orange3 and python3 completely. I downloaded Orange3-3.28.0-Python3.8.8.dmg.

When I install text add-on, the exact same error and waring message showed up. 

Following are some command I run in terminal, just fyi.
I run: pip install Orange3-Text

comes: -bash: pip: command not found.

Run: python

Showing:
WARNING: Python 2.7 is not recommended. 
This version is included in macOS for compatibility with legacy software. 
Future versions of macOS will not include Python 2.7. 
Instead, it is recommended that you transition to using 'python3' from within Terminal.

Python 2.7.16 (default, Jun  5 2020, 22:59:21) 
[GCC 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.29.20) (-macos10.15-objc- on darwin
Type "help", "copyright", "credits" or "license" for more information.

Run: python --version
Showing: Python 2.7.16

Run:type -a python
Showing:python is /usr/bin/python

**Comment by ajdapretnar** [comment]
Yes, the terminal won't help, because Orange works in a separate environment. You can see it in /Users/user/opt/miniconda3/envs (I think).

But the error is a strange one. It works on my Mac. We will have a look.

**Comment by Crystal-cxyz** [comment]
Okay. Thank you so much for helping.

**Comment by PrimozGodec** [comment]
> "Command failed: python python -m pip install text Orange3-Text==1.3.1 exited with non zero status.

@Crystal-cxyz from the command above it looks like Orange tries to install package named `text` besides `Orange3-Text==1.3.1` which is not a package that should be installed. I do not know why it happen but can you check something. 
When you open the add-on dialog can you check if there are maybe two packages with the name `text` on the list. The correct one is capitalized (`Text`) with version `1.3.1 ` besides. Is there maybe another one?

**Comment by PrimozGodec** [comment]
If you want to do manual installation of the add-on (as workaround) you can just type
```/Applications/Orange3.app/Contents/MacOS/python -m pip install Orange3-text```
in the terminal. This way you will instal Text addon in Orange's environment. But sure we want to find a reason for your error that it will not happen in the future.

**Comment by Crystal-cxyz** [comment]
@PrimozGodec Thank you. When I search (text), there is another one called textable version 3.1.8. Should I install that one?

**Comment by Crystal-cxyz** [comment]
I just run the commend: /Applications/Orange3.app/Contents/MacOS/python -m pip install Orange3-text

Here is what I got after the process:

  WARNING: The script tqdm is installed in '/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script nltk is installed in '/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed Orange3-text-1.3.1 beautifulsoup4-4.9.3 biopython-1.78 click-7.1.2 defusedxml-0.7.1 docx2txt-0.8 gensim-3.8.3 lxml-4.6.3 nltk-3.5 oauthlib-3.1.0 odfpy-1.4.1 pdfminer3k-1.3.4 ply-3.11 regex-2021.3.17 requests-oauthlib-1.3.0 setuptools-git-1.2 simhash-2.0.0 smart-open-4.2.0 soupsieve-2.2.1 tqdm-4.59.0 tweepy-3.10.0 ufal.udpipe-1.2.0.3 wikipedia-1.4.0
WARNING: You are using pip version 19.3.1; however, version 21.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


So I should upgrading pip again? I just removed them last time when I re-download orange.

**Comment by ajdapretnar** [comment]
@Crystal-cxyz It seems like Text got installed well. These were just warnings and you need not worry about them. Try running Orange and see if Text add-on appears.

**Comment by Crystal-cxyz** [comment]
@ajdapretnar  @PrimozGodec  Thank you so much. Now I can open my Orange with text mining function. I will try to play with it and go for my assignments.
