### ISSUE TITLE
Fastest embedding not working

### ISSUE THREAD

**Issue by ericjanvier** [biolab/orange3-text#640]
Fastext embedding not working in text mining module

- [ ] **What's wrong?**

When requesting a fastext embedding, there is a long wait and no response and I get the message
'some embedding were not successful'

- [ ] **How can we reproduce the problem?** 

Tried embedding for a set of French words or English words ...

- [ ] **What's your environment?**

- Operating system: OSX Big Sur 11.2.3 (20D91)
- Orange version: Orange 3.271
- How you installed Orange: via dmg package downloaded from orange3 web site

Mac Book pro 15 2019
Processor 2,3 GHz Intel Core i9 8 cœurs
16 Go 2400 MHz DDR4
Radeon Pro 560X 4 Go

**Comment by radcheb** [comment]
@ajdapretnar the embedding server looks down it returns `04 Gateway Time-out`.

**Comment by PrimozGodec** [comment]
We have had an issue with the certificate. Now it should work. Can you test?

**Comment by ericjanvier** [comment]
Thank you very much,
It works now.
Have a good day,
Eric

Eric Janvier
Tel 06 64 75 28 13
