### ISSUE TITLE
import doc.error!!

### ISSUE THREAD

**Issue by fatihcmc** [biolab/orange3-text#664]
Hello, when I add a document from outside, I get this error. What should I do?
![Screenshot_1](https://user-images.githubusercontent.com/18273064/119193221-ffcf6580-ba89-11eb-92d1-221464787a24.jpg)

**Comment by VesnaT** [comment]
The issue has been fixed in https://github.com/biolab/orange3-text/pull/626. Try updating the orange3-text add-on to 1.4.0 version.
