### ISSUE TITLE
Wikipedia does not exist

### ISSUE THREAD

**Issue by triandi30** [biolab/orange3-text#685]
Please help I have installed add in text mining but only wikipedia doesn't exist, how do I display wikipedia in my orange.

I use windows 10, I downloaded orange from the official site

**Comment by triandi30** [comment]
I use windows 10, I downloaded orange from the official site

**Comment by ajdapretnar** [comment]
Yes, the dependency is broken and the widget will most likely be removed in the future.

**Comment by ajdapretnar** [comment]
Fixed in #825.
