### ISSUE TITLE
CondaVerificationError: The package for orange3-text located appears to be corrupted

### ISSUE THREAD

**Issue by fahminlb33** [biolab/orange3-text#696]
**Describe the bug**
I can't install the latest version of `orange3-text` using Miniconda (conda 4.10.3). It appears to be the package is corrupted. After some checking I found out there might be a problem with the file name in the shipped package at this location:

```
orangecontrib\text\widgets\tests\data\good
```

There is a single file with Unicode text file name `sample_txt_┼╛.txt` that makes `conda` failed to find that file and resulting in failure of orange3-text installation (screenshot attached).

**To Reproduce**
I'm starting a fresh installation of Orange using Miniconda. Steps to reproduce the behavior:
1. Open miniconda prompt.
2. Run `conda install -c conda-forge -n orange3 Orange3==3.29.3 Orange3-Text`
3. See error

**Expected behavior**
The package to be installed.

**Orange version:**
conda-forge/win-64::orange3-3.29.3-py39h2e25243_0

**Text add-on version:**
conda-forge/noarch::orange3-text-1.4.0-pyhd8ed1ab_0

**Screenshots**

```
Preparing transaction: done
Verifying transaction: failed

CondaVerificationError: The package for orange3-text located at E:\app-store\bin\miniconda3\pkgs\orange3-text-1.4.0-pyhd8ed1ab_0
appears to be corrupted. The path 'site-packages/orangecontrib/text/widgets/tests/data/documents/good/sample_txt_ž.txt'
specified in the package manifest cannot be found.

CondaVerificationError: The package for orange3-text located at E:\app-store\bin\miniconda3\pkgs\orange3-text-1.4.0-pyhd8ed1ab_0
appears to be corrupted. The path 'site-packages/orangecontrib/text/widgets/tests/data/good/sample_txt_ž.txt'
specified in the package manifest cannot be found.
```

![image](https://user-images.githubusercontent.com/8360880/127772266-9d2ff7d2-fa47-4a34-a8bc-19a605169759.png)

**Operating system:**
Windows 10  21H1 Build 19043.1110

**Comment by ajdapretnar** [comment]
My assumption based also on https://github.com/biolab/orange3-text/issues/570 is that Chinese locale cannot handle all Unicode characters. We cannot reproduce this, but the error does seem to pop up now and then.

**Comment by ajdapretnar** [comment]
Closed due to inactivity.
