### ISSUE TITLE
Unfocused selections in table components hard to see

### ISSUE THREAD

**Issue by lanzagar** [biolab/orange3-text#711]
When I (on Linux) select some rows in Table, Rank, ... or other widgets with tabular components the style changes to blue background and white foreground text. It stays the same after the widget loses focus (e.g. I click in some other widget).
This appears to be different on MacOS (and maybe Windows?), where there is an additional style for selections when out-of-focus. These are less noticable - the background changes from blue to light grey, and sometimes very hard to read, when text stays white too (almost white on white).
As we don't need the differentiation of "unfocused selections" it would be better to try and force the same (focused) style for selections all the time - even when unfocused.

**Comment by ajdapretnar** [comment]
@janezd I prepared the PR, but something isn't right. Now the selection has blue background (which is ok) with black font (which is not). I am obviously missing something and would appreciate the hint.
