### ISSUE TITLE
Text Widgets missing / Missing Node definitions

### ISSUE THREAD

**Issue by happyskykai** [biolab/orange3-text#714]
Hi all,

I am using Orange 3.29 on a Mac and installed the Text add-on via the add-on installer interface.

After restarting Orange3, the Text widgets are not showing up on the left side, but in the add-on interface it clearly is marked as installed.

I ran a workflow from a colleague that used widgets from Orange3-Text, and it gives me the following error message:

![image](https://user-images.githubusercontent.com/89873223/131568083-2b8bb27b-ee00-4997-a91f-404d5d3a5b1f.png)

Can anybody help me?

Thanks a lot in advance!

Kai

**Comment by ajdapretnar** [comment]
Please explain how you installed Orange (dmg or Anaconda)?

**Comment by happyskykai** [comment]
@ajdapretnar Thanks for the quick response!
 
I installed it via the dmg and just pulled the app into my applications folder.

**Comment by happyskykai** [comment]
@ajdapretnar Any idea how I could potentially fix it?

**Comment by PrimozGodec** [comment]
Gensim has issues with their builds. I proposed a PR that limits Gensim to <4 #718 When it is merged we must propose a release of text addon.

**Comment by PrimozGodec** [comment]
It should be fixed now with the new release. Please try to upgrade orange3-text and let us know if it is working now.

I am closing this PR but please reopen it in case that it is still not working.
