### ISSUE TITLE
Tweepy Truncates Retweets

### ISSUE THREAD

**Issue by nikicc** [biolab/orange3-text#73]
The problem occurs with re-tweets of long tweets. For example when searching for `#happy` in content among others I get this tweet:
<img width="945" alt="screen shot 2016-07-02 at 00 09 24" src="https://cloud.githubusercontent.com/assets/713026/16535644/5328e90c-3fe9-11e6-97f0-0b316c12b185.png">
Note that there is no `#happy` inside the content. When I checked this tweet directly [on twitter](https://twitter.com/HauteDerriere/status/748663666514468865) I came up with a plausible explanation. If some tweet is a re-tweet then a `RT` token along with an username is prepended to the tweet and it is afterwards truncated to 140 character.

The easiest way to reproduce this is to search for some hashtag and then also search for it in CorpusViewer and watch if some documents are filtered out.

@s-alexey can we do something about it?

**Comment by s-alexey** [comment]
We can filter out all retweets by adding `-filter:retweets` to query.

**Comment by nikicc** [comment]
> We can filter out all retweets by adding -filter:retweets to query.

Yes this would be nice 👍 We could add this as an option to gui.

**Comment by nikicc** [comment]
Resolved with #89.
