### ISSUE TITLE
I've tried reinstalling several times, but I still get errors

### ISSUE THREAD

**Issue by zika1997** [biolab/orange3-text#762]
![20214916024924](https://user-images.githubusercontent.com/96226334/146323467-a7ca349a-abec-48a6-8c36-eef413b91e09.png)
![20214916024945](https://user-images.githubusercontent.com/96226334/146323486-9a16fb1a-54c8-4cda-b71a-2cb6923b1cc5.png)
I want to use english，but here is none. 
And there is red ×.
![IMG_9036(1)](https://user-images.githubusercontent.com/96226334/146324236-ab32991c-4393-45b9-938b-3ce51fb734b6.JPG)

Please help me，thanks.

**Comment by ajdapretnar** [comment]
It looks like the NLTK data was no properly downloaded. You need to be connected to the internet for the first time when using Preprocess Text. Alternatively, check your proxy settings.

**Comment by ajdapretnar** [comment]
Closed due to inactivity.
