### ISSUE TITLE
Twitter Restricted My Access for using Tweeter Widget

### ISSUE THREAD

**Issue by rafacost** [biolab/orange3-text#770]
**Describe the bug**
I created a simple sentiment analysis workflow, used my api key from twitter.
Searched only 100 tweets. Next morning my api key were revoked.
They say that I sent unsolicited @mentions which is prohibited by our Automation Rules and the Twitter Rules on spam.

**To Reproduce**
Create an API key on twitter developer portal
Use it on twitter widget

**Expected behavior**
Get your api key revoked on twitter.

**Orange version:**
Orange - About - version number 3,31,3

**Text add-on version:**
Options - Add-ons - version numbe 1,6,2

**Operating system:**
Windows, OSX or Linux? Which version? Does it matter? Windows 11

**Comment by ajdapretnar** [comment]
This is certainly not an issue of the Twitter widget. It doesn't have any capability to post anything anywhere. You need to look for the problem elsewhere.
