### ISSUE TITLE
Extract Keywords: manual selection doesn't work all the time

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-text#823]
**Describe the bug**
Manual selection in Extract Keywords doesn't always work as expected. I tried to select random words from the list using Cmd (Ctrl) for selection. It works up to a certain point, then it deselects everything from before and selects just the item that is clicked on.

**To Reproduce**
1. Extract some keywords with Extract Keywords.
2. Use cmd/ctrl to select random rows in the table.
3. Make sure to use scroll to not stay in the same view all the time.

**Expected behavior**
Cmd/Ctrl works as expected - selection is retained at all times.

**Orange version:**
3.33.dev

**Text add-on version:**
1.7.0

**Comment by PrimozGodec** [comment]
It is duplicate of https://github.com/biolab/orange3-text/issues/811

**Comment by ajdapretnar** [comment]
Sorry, didn't see that.
