### ISSUE TITLE
Corpus Viewer: speedup options?

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-text#843]
**Is your feature request related to a problem? Please describe.**
I have 180,000 documents in my corpus. Corpus Viewer seems particularly slow when opening. Data Table is faster.

**Describe the solution you'd like**
Any chance to speed up Corpus Viewer?

**Describe alternatives you've considered**
/

**Comment by PrimozGodec** [comment]
Closing via https://github.com/biolab/orange3-text/pull/906
