### ISSUE TITLE
Un-helpfull/unclear expressions in widget description

### ISSUE THREAD

**Issue by zalagruden** [biolab/orange3-text#876]
The description of the Document embedding Widget in Orange Documentation is tautological and pleonastic. 

Please, rewrite the description to make it understandable that the widget changes text documents into numbers. 

<img width="648" alt="Screenshot 2022-06-30 at 13 40 20" src="https://user-images.githubusercontent.com/102144841/176669504-afdfe519-cadf-4510-84cd-024f9b4f91c2.png">

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Orange version:**
Orange - About - version number.

**Text add-on version:**
Options - Add-ons - version number.

**Screenshots**

**Operating system:**
Windows, OSX or Linux? Which version?

**Additional context**

**Comment by ajdapretnar** [comment]
I think the description is exact and precise. It mentions vector space and which models are used.
Saying "it changes text documents into numbers" is incorrect and imprecise. This is a simplistic version we would use in short tutorials, not in documentation.
But if required, I can try to add a simple English explanation below the description.
