### ISSUE TITLE
Number of optimal topics (k) in LDA models

### ISSUE THREAD

**Issue by NAsic123** [biolab/orange3-text#880]
**Is your feature request related to a problem? Please describe.**
In Orange, you have to type the number of topics you want to have in the LDA model. Sometimes you do now know from the theory how many topics are the most optimal to describe your corpus. 

**Describe the solution you'd like**
I want to know how do we calculate the optimal number of topics (k) in the LDA method in Orange?
I know the most useful way to do that is to know the coherence for each model with k numbers and the models with the highest coherence is the one that determines how many topics should we have in the LDA model.

**Describe alternatives you've considered**
I found these useful metrics and want to know if anyone from you knows how to calculate these metrics in Orange?

https://cran.r-project.org/web/packages/ldatuning/vignettes/topics.html 

Or I guess that you have to calculate these metrics in per example R Studio, figure out how many k topics are the most desirable for your corpus and then run the LDA in Orange?

**Comment by NAsic123** [comment]
@ajdapretnar Thank you so much for these articles and answers. Can I ask you how you personally as a researcher decide on the number of topics you define in Orange? Is it arbitrary or based on the theory (if it is given)? Or do you 'experiment' and type 10, 15 etc. number of themes and see how coherence changes?

I have a dilemma with defining a number of topics and want to ask others how they decide about it.

**Comment by ajdapretnar** [comment]
I refer to similar research and try 10 and 20 topics. The difference between 10 and 15 is not really significant. More often than not, a single topic will just be split into smaller topics or subtopics. So in the end, it comes down to interpretability. Do 10 topics make sense? Then go for it. Having 12 topics will not change much, if anything.

I never use coherence.

**Comment by NAsic123** [comment]
@ajdapretnar Thank you so much for your advice.
