### ISSUE TITLE
Corpus Widget doesn`t work

### ISSUE THREAD

**Issue by alexanderfussan** [biolab/orange3-text#892]
**Describe the bug**
After loading a pkl file an error occures when using the corpus viewer widget o the preprocess widget. This error occures in Release 3.32, there was no problem with this pkl file in Release 3.27 for instance.

**To Reproduce**
1. Load pkl file with Corpus Widget
2. Try to use the Corpus Viewer or Preprocess Widget

**Expected behavior**
No error message

**Orange version:**
3.32

**Text add-on version:**
Options - Add-ons - version number.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/111502928/187145040-611530c2-2053-4fa5-be0f-60814753f635.png)
![grafik](https://user-images.githubusercontent.com/111502928/187145166-fd5609f6-1a95-42a1-9eb9-9459b059eb0a.png)

**Operating system:**
Windows 11

**Additional context**

**Comment by ajdapretnar** [comment]
Please report also the version of the Text add-on.

**Comment by alexanderfussan** [comment]
Text 1.11.0

**Comment by PrimozGodec** [comment]
I know the issue is old, but I will try anyway. Do you maybe have an example of the pickle file that causes problems? Does the error still appear in the newest text addon?

**Comment by PrimozGodec** [comment]
Since we cannot reproduce this issue, I am closing it. Please reopen the issue if you can reproduce it. The example of a pickle that doesn't loads would be helpful.
