### ISSUE TITLE
bag of words stuck and a RecursionError exception was reported

### ISSUE THREAD

**Issue by bobcyw** [biolab/orange3-text#909]
**Describe the bug**
The interface of bag of words is stopped at 90% progress, and the log shows an abnormal error of RecursionError.

**To Reproduce**
1. Drag a corpus to the interface and select Grimm's Fairy Tale
2. Set the next corpus to bag of words will get this error

**Expected behavior**
Hope bag of words works fine

**Orange version:**
Orange - About - 3.33.0

**Text add-on version:**
Options - Add-ons - 1.11.0

**Screenshots**

**Operating system:**
Windows 11

**Additional context**
![2022-10-06](https://user-images.githubusercontent.com/4155602/194290641-1d4f5eb9-dec3-400d-a0ec-f4d0079df9bf.png)

**Comment by PrimozGodec** [comment]
Orange3-text 1.12.0 is now released. @bobcyw, please try upgrading the Text add-on from the add-ons dialogue. The bag of words should work now. Please let us know if it works for you.

**Comment by bobcyw** [comment]
Awesome, I just updated to 1.12.0 and the problem has been fixed, thanks

**Comment by PrimozGodec** [comment]
Great, thanks for reporting
