### ISSUE TITLE
Documentation for Annotated Corpus Map

### ISSUE THREAD

**Issue by wvdvegte** [biolab/orange3-text#958]
**Is your feature request related to a problem? Please describe.**
Annotated Corpus Map is lacking documentation. Yet it is a rather complex widget and it's hard to figure out what it does.

**Describe the solution you'd like**
A description of how to use it, with example(s) would be nice

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by PrimozGodec** [comment]
Thank you for the report. We forgot a bit about the documentation. The widget would need some good documentation.
