### ISSUE TITLE
Error : Orange3-text addon cannot be installed on Apple Silicon

### ISSUE THREAD

**Issue by asmasbai** [biolab/orange3-text#974]
I installed Orange3 on my Mac os Mojave 10.14.6. The version of Orange 3 is 3.35.0
I used the dmg installer
I needed to install add-ons : Installer - > Add-ons
I got this error: 
![Capture d’écran 2023-05-10 à 10 20 23](https://github.com/biolab/orange3/assets/51519011/5991846f-ae18-41fb-91c6-275cd9bd021c)

My internet is working just fine, 
I don't use any proxy, I even tried to connect with my 4G I always have the same error.

the details of the error are as follow: 

> Traceback (most recent call last):
>   File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/orangecanvas/application/addons.py", line 510, in <lambda>
>     lambda config=config: (config, list_available_versions(config)),
>   File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/orangecanvas/application/utils/addons.py", line 364, in list_available_versions
>     response = session.get(PYPI_API_JSON.format(name=p))
>   File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/sessions.py", line 600, in get
>     return self.request("GET", url, **kwargs)
>   File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/sessions.py", line 745, in send
>     r.content
>   File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/models.py", line 899, in content
>     self._content = b"".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b""
>   File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/models.py", line 816, in generate
>     yield from self.raw.stream(chunk_size, decode_content=True)
>   File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/response.py", line 935, in stream
>     data = self.read(amt=amt, decode_content=decode_content)
>   File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/response.py", line 874, in read
>     data = self._raw_read(amt)
>   File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/response.py", line 809, in _raw_read
>     data = self._fp_read(amt) if not fp_closed else b""
>   File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/response.py", line 794, in _fp_read
>     return self._fp.read(amt) if amt is not None else self._fp.read()
>   File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cachecontrol/filewrapper.py", line 96, in read
>     self._close()
>   File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cachecontrol/filewrapper.py", line 76, in _close
>     self.__callback(result)
>   File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cachecontrol/controller.py", line 353, in cache_response
>     self._cache_set(cache_url, request, response, body, expires_time)
>   File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cachecontrol/controller.py", line 274, in _cache_set
>     self.serializer.dumps(request, response, body),
>   File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cachecontrol/serialize.py", line 54, in dumps
>     u"strict": response.strict,
> AttributeError: 'HTTPResponse' object has no attribute 'strict'

**Please, i need support for this issue so i can complete a project.**
Thanks in advance

**Comment by PrimozGodec** [comment]
@asmasbai, since I believe the installer problem is now resolved (after clearing the cache), I moved this issue to orange3-text because of the orange3-text install issue. We found out that the issue is [lxml](https://github.com/lxml/lxml) library that orange3-text uses which still didn't release wheels for Apple silicon processors (arm), which means that the package is built from source on Macs that have Apple M1/M2 processors. I will propose the pull request to remove this library from the requirements and try to make a new orange3-text release soon. Please stay tuned.

**Comment by asmasbai** [comment]
Thanks a lot for your reactivity, you are the best :) It works just fine
Have a nice day
