### ISSUE TITLE
Word Cloud sometimes doesn't show words in Words & Weights list

### ISSUE THREAD

**Issue by wvdvegte** [biolab/orange3-text#987]
**Describe the bug**
Depending on the box size, Word Cloud may not display all the words in the list

**To Reproduce**
The word cloud shown can be generated with the enclosed workflow and data
There are only three words (or in this case, compound keywords, because I kept these together) in the dataset, yet the one with the second-highest weight isn't shown if the box size is like this:
![image](https://github.com/biolab/orange3-text/assets/55989717/5febd37b-6622-4ed2-9de4-b3b88ff96fff)
... but if the box size is reduced like this, it is shown:
![image](https://github.com/biolab/orange3-text/assets/55989717/918c3d61-f51c-44fc-95f0-d456a8b1f596)

**Expected behavior**
All words in the list should be shown in the word cloud

**Orange version:**
3.35

**Text add-on version:**
1.13.1

**Operating system:**
Mac OS Ventura 13.4.1 on Silicon

[Archive.zip](https://github.com/biolab/orange3-text/files/12122121/Archive.zip)

**Comment by PrimozGodec** [comment]
Thank you for reporting the issue. Since the problem originates from the underlying javascript library we use to plot the word cloud, I am updating the library to the newest version in #988. It solves the problem (at least on my computer).
